In [ ]:
from google.colab import drive
drive.mount("/content/MyDrive")

Mounted at /content/MyDrive

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
!ls /content/MyDrive/MyDrive/тексты/дз/train.csv

/content/MyDrive/MyDrive/тексты/дз/train.csv

In [ ]:
df = pd.read_csv('/content/MyDrive/MyDrive/тексты/дз/train.csv', encoding='ISO-8859-1')

In [ ]:
df_test = pd.read_csv('/content/MyDrive/MyDrive/тексты/дз/test.csv', encoding='ISO-8859-1')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2351 entries, 0 to 2350
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2351 non-null   int64
 1   Hotel_name    2351 non-null   object
 2   Review_Title  2136 non-null   object
 3   Review_Text   2351 non-null   object
 4   Rating        2351 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 92.0+ KB

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2352 entries, 0 to 2351
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2352 non-null   int64
 1   Hotel_name    2352 non-null   object
 2   Review_Title  2143 non-null   object
 3   Review_Text   2352 non-null   object
dtypes: int64(1), object(3)
memory usage: 73.6+ KB

In [ ]:
df

        Id  ... Rating
0        0  ...   80.0
1        1  ...  100.0
2        2  ...   71.0
3        3  ...   86.0
4        4  ...   86.0
...    ...  ...    ...
2346  2346  ...   80.0
2347  2347  ...   71.0
2348  2348  ...  100.0
2349  2349  ...   80.0
2350  2350  ...   71.0

[2351 rows x 5 columns]

In [ ]:
df.isna().sum()

Id                0
Hotel_name        0
Review_Title    215
Review_Text       0
Rating            0
dtype: int64

In [ ]:
df_test.isna().sum()

Id                0
Hotel_name        0
Review_Title    209
Review_Text       0
dtype: int64

In [ ]:
df.drop('Id', axis=1, inplace=True)

In [ ]:
df_test.drop('Id', axis=1, inplace=True)

In [ ]:
def clean_sent(sentence):
    sentence = re.sub(r'\s+', ' ', sentence)
    sentence = re.sub(r'\d+', '', sentence)
    cleared_sentence = re.sub(r'[^\w+\s]', '', sentence).lower()
    return cleared_sentence

In [ ]:
import nltk

In [ ]:
from nltk import WordNetLemmatizer, pos_tag
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
from nltk import wordnet, pos_tag
def get_wordnet_pos(treebank_tag):
    my_switch = {
        'J': wordnet.wordnet.ADJ,
        'V': wordnet.wordnet.VERB,
        'N': wordnet.wordnet.NOUN,
        'R': wordnet.wordnet.ADV,
    }
    for key, item in my_switch.items():
        if treebank_tag.startswith(key):
            return item
    return wordnet.wordnet.NOUN

In [ ]:
def my_lemmatizer(sent):
    lemmatizer = WordNetLemmatizer()
    tokenized_sent = sent.split()
    pos_tagged = [(word, get_wordnet_pos(tag))
                 for word, tag in pos_tag(tokenized_sent)]
    return ' '.join([lemmatizer.lemmatize(word, tag)
                    for word, tag in pos_tagged])

In [ ]:
df

                          Hotel_name  ... Rating
0                         Park Hyatt  ...   80.0
1                     Hilton Chennai  ...  100.0
2                  The Royal Regency  ...   71.0
3                             Rivera  ...   86.0
4                         Park Hyatt  ...   86.0
...                              ...  ...    ...
2346           Hyatt Regency Chennai  ...   80.0
2347                   New Woodlands  ...   71.0
2348               Samudra Residency  ...  100.0
2349           The Residency Chennai  ...   80.0
2350  Cloud Nine Serviced Apartments  ...   71.0

[2351 rows x 4 columns]

In [ ]:
df_test

                              Hotel_name  ...                                        Review_Text
0                        ITC Grand Chola  ...  On the night of my arrival from NY I had a min...
1                          Hotel Pandian  ...  Not so great.  But it is still acceptable. Bit...
2     Oyo Rooms Guindy Olympia Tech Park  ...  Been a good place to stay for people who visit...
3                OYO Apartments Saidapet  ...  Not worth of the money we paid.worst ac.no wat...
4                  Ramada Chennai Egmore  ...  A well located hotel, with decent sized rooms ...
...                                  ...  ...                                                ...
2347                  Lemon Tree Chennai  ...  Compared to other lemon tree stay, this was bi...
2348  Oyo Rooms T Nagar Off Pondy Bazaar  ...  unpleasant stay. not easy task to reach. Morni...
2349             VGP Golden Beach Resort  ...  Quality of service is too bad. We arrived 12.3...
2350                    The Park Chennai  ...  I am not sure why someone wants to spend that ...
2351                           Peace Inn  ...  I visited Chennai in the summer of 2014. This ...

[2352 rows x 3 columns]

In [ ]:
df.Review_Text[:50]

0     Excellent room and exercise facility. All arou...
1     Very comfortable and felt safe. \r\nStaff were...
2     Not worth the rating shown. Service is not goo...
3     First of all nice & courteous staff, only one ...
4     Overall ambience of the hotel is very good. In...
5     I reached the hotel by car, felt good for co-o...
6     The hotel is pretty clean with excellent beddi...
7     No hot water.wifi limited to lobby. Average cl...
8     Hotel staff are not co-ordinating well for the...
9     Location and cleanliness is good. But as far a...
10    It's amazing and I got so many benefits from t...
11    Nice place,excellent value for money.\r\n\r\nO...
12    The activity was not conducted in the hotel. T...
13    Booked a Deluxe Room with an occupancy for 2 p...
14    Hotel is good with AC and WiFi. Staff in the h...
15    The hotel is great and its location makes it e...
16    This hotel is great for overnight stay if you ...
17    It was OK. Not worth as shown the pics in make...
18    Great Location for my kind of business. Proxim...
19    The hotel location is good... but the beds are...
20    This place is infested with roaches. The towel...
21    Located centrally. Value for money. I should s...
22    My experience of the hotel was very nice. The ...
23    I had visited this hotel for official trip. Go...
24                                                 Good
25    Very nice hotel with excellent accommodations ...
26    It was good. Food was OK. Location is much con...
27    Akash Inn one of the best place in Chennai. So...
28    Had a good stay at this hotel for a weeks time...
29    It was great, the stay was perfect. Perfect ro...
30    Let's see:\r\nExpedia booking didn't come thru...
31    Gues dont book any thing from the site.it's a ...
32    Hotel does not provide facilities as per three...
33    I made a booking for my guests, my guests were...
34    The stay was very good .....the hotel had a go...
35    I Have stayed here for 3 days. Prompt service ...
36    Room service, Reception Hospitality, Cleanline...
37    I stayed in this hotel in the month of June. i...
38    Nice hotel nice food nice drinks OK service OK...
39    The staff was really helpful. Unfortunately, w...
40    Got a good deal over the long weekend . Otherw...
41    We were in Chennai for admission of my Son at ...
42    Worth for money. We stayed there for 3 days 2 ...
43    Good hotel. Clean and neat. Friendly staff .. ...
44    I went on for a honeymoon with my bunny. We bo...
45    The management of this hotel is not upto the e...
46    in our journey we were worried about the place...
47    Clean, comfortable and hotel staff very cooper...
48                 i enjoyed lot .excellent hospitality
49    Isolated place, very difficult to find the exa...
Name: Review_Text, dtype: object

In [ ]:
df_test.Review_Text[:50]

0     On the night of my arrival from NY I had a min...
1     Not so great.  But it is still acceptable. Bit...
2     Been a good place to stay for people who visit...
3     Not worth of the money we paid.worst ac.no wat...
4     A well located hotel, with decent sized rooms ...
5     It was a fantastic stay in the hotel. The staf...
6     It's really hard to believe that now with 3-4k...
7     Compared to other lemon tree stay, this was bi...
8     One of my close friend referred this hotel and...
9                   Pleasant stay, great breakfast too.
10    bkfst not so great someways was cold. Service ...
11    The location good. The service good. The room ...
12    Room Service is terribly slow. For 2 bottle of...
13    Facilities: Nice ; Value: Fantastic; Service: ...
14    Other than proximity to the airport and the ro...
15    VERY FRIENDLY STAFF IN ALL AREAS, VERY GOOD  I...
16    Not worth it. The service is bad. Hotel staff ...
17    I had great stay in this hotel, this is the fi...
18    Ideally located average hotel, cleanliness is ...
19    Good considering its location but still could ...
20    This place has really very good ambiance. The ...
21    It was a good experience. We had a very wonder...
22    Good Hospitality!!!!!!!!!!Good Hospitality!!!!...
23    We booked this hotel for visa interview at us ...
24    Ac is not good..bed is not that much good.. it...
25    Hotel is old one. Bathroom is not good. This i...
26    Nice stay. Complementary breakfast was good. O...
27    I booked the room for two days, but I have got...
28    Business trip for two days, very nice hotel, l...
29    Good hotel located nearest to railway station....
30    Unlike earlier when everything was billed and ...
31    You get what you pay for. It is very convenien...
32    Very good room and nice facilities, breakfast ...
33    Hotel is very nice with nice location we visit...
34    It was a great place to spend 4 days with my f...
35    Its really nice place to stay especially for b...
36    Stay was short -- only for one night -- but wa...
37    Excellent experience starting from the pickup ...
38    We had a very good stay. All the staff were at...
39    Overall good , room are need& regular cleaning...
40    Value for money if booked through MMT. Locatio...
41    I go to room verynice service excellent of ant...
42    Service is very slow, issues with toilet, book...
43    The additional bed provided was a disgrace\r\n...
44    Overall a good place to stay. Food was good. R...
45                     Attention to details! Fantastic!
46    Hotel restaurant is very bad and very costly 4...
47    Hotel staff was friendly and courteous.\r\nRoo...
48    The overall experience was good in the hotel. ...
49    Nice hotel near airport. Booked it for my sist...
Name: Review_Text, dtype: object

In [ ]:
clean_sent('kdjf   ^hwd@ df err% kkk     @@:: fjjkjkwd (9  888 333 hhh')

'kdjf hwd df err kkk  fjjkjkwd    hhh'

не идеально, но для сплита пойдет (сплит убьет эти пробелы)

In [ ]:
my_lemmatizer('write wrote written')

'write write write'

In [ ]:
import nltk

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
sw_eng = set(stopwords.words('english'))
list(sw_eng)[:4]

['herself', 'yourself', 'few', 'only']

Приступим к чистке текстов отзывов

In [ ]:
df['Review_Text'] = df['Review_Text'].apply(clean_sent)

In [ ]:
df_test['Review_Text'] = df_test['Review_Text'].apply(clean_sent)

In [ ]:
df['Review_Text'] = df['Review_Text'].apply(lambda sentence: ' '.join([word for word in sentence.split() if word not in sw_eng]))

In [ ]:
df_test['Review_Text'] = df_test['Review_Text'].apply(lambda sentence: ' '.join([word for word in sentence.split() if word not in sw_eng]))

In [ ]:
!pip install autocorrect

Requirement already satisfied: autocorrect in /usr/local/lib/python3.7/dist-packages (2.6.1)

In [ ]:
from autocorrect import Speller
spell = Speller()

In [ ]:
df['Review_Text']

0       excellent room exercise facility around atmosp...
1       comfortable felt safe staff helpful respectful...
2       worth rating shown service good room well main...
3       first nice courteous staff one con stay time c...
4       overall ambience hotel good room facilities ne...
                              ...
2346    impressive service staff areas good restaurant...
2347    new woodlands chennai gave homely experience l...
2348    awesome liked neatness maintenance facilities ...
2349    overall experience good however wifi getting d...
2350    cool luxurious cottage stay families couples e...
Name: Review_Text, Length: 2351, dtype: object

In [ ]:
df['Review_Text'] = df['Review_Text'].apply(lambda sentence: ' '.join([spell(word) for word in sentence.split()]))

In [ ]:
df_test['Review_Text'] = df_test['Review_Text'].apply(lambda sentence: ' '.join([spell(word) for word in sentence.split()]))

In [ ]:
df['Review_Text']

0       excellent room exercise facility around atmosp...
1       comfortable felt safe staff helpful respectful...
2       worth rating shown service good room well main...
3       first nice courteous staff one con stay time c...
4       overall audience hotel good room facilities ne...
                              ...
2346    impressive service staff areas good restaurant...
2347    new woodlands chennai gave home experience lux...
2348    awesome liked weakness maintenance facilities ...
2349    overall experience good however wifi getting d...
2350    cool luxurious cottage stay families couples e...
Name: Review_Text, Length: 2351, dtype: object

In [ ]:
df['Review_Text'] = df['Review_Text'].apply(my_lemmatizer)

In [ ]:
df_test['Review_Text'] = df_test['Review_Text'].apply(my_lemmatizer)

In [ ]:
df['Review_Text']

0       excellent room exercise facility around atmosp...
1       comfortable felt safe staff helpful respectful...
2       worth rating show service good room well maint...
3       first nice courteous staff one con stay time c...
4       overall audience hotel good room facility need...
                              ...
2346    impressive service staff area good restaurant ...
2347    new woodland chennai give home experience luxu...
2348    awesome like weakness maintenance facility rea...
2349    overall experience good however wifi get disco...
2350    cool luxurious cottage stay family couple enjo...
Name: Review_Text, Length: 2351, dtype: object

In [ ]:
df

        Id  ... Rating
0        0  ...   80.0
1        1  ...  100.0
2        2  ...   71.0
3        3  ...   86.0
4        4  ...   86.0
...    ...  ...    ...
2346  2346  ...   80.0
2347  2347  ...   71.0
2348  2348  ...  100.0
2349  2349  ...   80.0
2350  2350  ...   71.0

[2351 rows x 5 columns]

Добавим колонку об отсутствии заголовка (о наличии np.nan в заголовке отзыва)

In [ ]:
df['Review_Title_Missed'] = df['Review_Title'].isna().apply(lambda x: 1 if x else 0)

In [ ]:
df_test['Review_Title_Missed'] = df_test['Review_Title'].isna().apply(lambda x: 1 if x else 0)

In [ ]:
df

        Id                      Hotel_name  ... Rating Review_Title_Missed
0        0                      Park Hyatt  ...   80.0                   0
1        1                  Hilton Chennai  ...  100.0                   0
2        2               The Royal Regency  ...   71.0                   0
3        3                          Rivera  ...   86.0                   0
4        4                      Park Hyatt  ...   86.0                   0
...    ...                             ...  ...    ...                 ...
2346  2346           Hyatt Regency Chennai  ...   80.0                   1
2347  2347                   New Woodlands  ...   71.0                   0
2348  2348               Samudra Residency  ...  100.0                   0
2349  2349           The Residency Chennai  ...   80.0                   0
2350  2350  Cloud Nine Serviced Apartments  ...   71.0                   0

[2351 rows x 6 columns]

In [ ]:
df['Review_Title'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
2346     True
2347    False
2348    False
2349    False
2350    False
Name: Review_Title, Length: 2351, dtype: bool

In [ ]:
df['Review_Title']

0                                       Refuge in Chennai
1                                          Hilton Chennai
2       No worth the rating shown in websites. Pricing...
3                                               Good stay
4                                       Needs improvement
                              ...
2346                                                  NaN
2347                                         Homely villa
2348                    Nice accommodation and facilities
2349           The Residency Good Centrally located Hotel
2350                  Homely stay with comfort and luxury
Name: Review_Title, Length: 2351, dtype: object

Заменим наны в заголовке на первые два слова текста отзыва

In [ ]:
df['Review_Title'][df['Review_Title'].isna() == True] = df['Review_Text'].apply(lambda x: ' '.join(x.split()[:2]) if len(x.split()) >= 2 else x)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_test['Review_Title'][df_test['Review_Title'].isna() == True] = df_test['Review_Text'].apply(lambda x: ' '.join(x.split()[:2]) if len(x.split()) >= 2 else x)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
print(*set(df['Review_Title'].value_counts().index), sep='\n')

Location is great
good location
hotel decent
Clean rooms but no activities available
Great Hotel for US Visa
It was an excellent stay with great experience
comfort in noisy city.
A good option in Chennai
Not kept well anymore!
Hygienic, nice ambience, good stay. Good service.
very good exeirience
Good location but not with the services
Comfort level and services are on the best
good place
BKR Grand
Not good and clean
Good hotel to stay with good roms
ac wasnt
Excellent stay & value for money
Ramada Egmore
Decent budget hotel at good location
Nice stay experience.
Good hotel, pleasant stay
Decent place with well-maintained rooms
saw much
Small but cosy
Nice hotel. Clean
Worst room on make my trip
Great service and really nice hotel.
Nice hotel attached to the Shopping Mall
Good management, food and services
OK not bad
Not a good breakfast
Good hotel in poor location
Great location & good for business travellers
Affordable within budget
Excellent location and spacious rooms
Good hotel for the price and great neighborhood.
Not a worthy stay
Good time with courtyard Marriott
Awesome resort with good facilities
Five star service
Waste of money
hotel room
Polite staff and peaceful location
A decent stay with some problems.
Worst hotel, don't even thing about it!
Good location and helpful staff
Decent hotel but service is slow
Location is ideal for those who come for shopping
Wi-Fi connection was arranged
wonderful staff
Nice hotel close to the US embassy.
cleanliness in bed sheet and room tobe improved
Excellent hotel stay
Very Poor
hotel staff
hotel really
Wonderful stay
Good for business stay
Good for business Stay
four star
hotel good
Great place to unwind after flying!
Good hotel
Superb hotel with great food and facilities
Food was good because of good cook. Good service !
Wonderful stay at Savera
Review and rating
Excellent hotel to stay with 3 members
Excellent hotel to stay
Prime location and decent stay
A business Favourable Hotel and Excellent Food, Service!!!!
Good Resort for weekend
Excellent to stay
Hotel located well and staff are very friendly
Complimentary Breakfast was provided
Conveniently located with clean rooms, good food
Well located, brand hotel
very good
Pleasant experience & quick service
impressive service
Decent hotel, right price in place
get veg
Good services and wonderful stay
Room is good and even response
We were well taken care of. Highly Recommended!
bath room
just like home
Good value for money and friendly staff
Awesome experience and friendly staff
Everything was very good
Omr h?tel
A good budget stay
Excellent hotel for long term stay
great service
Worst Hotel ever seen in my life
Neat hotel with OK staff
Dinner was not provided for makemytrip
Decent hotel with good food
Gundas are receptionist here
Average stay
Comfort in the heart of Chennai
Good for business travel.
Good room and service
Good hotel to stay with superb service
hotel kind
Average food quality and service
Pleasant stay but food needs improvement
Very welcoming staff & Airport pickup is convenient.
One of the budget hotel to stay in Saligramam
It's very Good
Comfortable to stay and good food
Good hotel but difficult for communicate
Overall very good experience
Poor Room Service
Comfortable room & value for money
nice slavery
staff become
Clean ,Modern Nice.
Old n noisy
Good stay at economy prices
Nice hotel very near to Marina Beach
A recommended budget hotel
Bit costly hotel
Decent stay
Poor services
Good accomodation to stay
Located well with good appearance
Awesome & luxurious hotel to stay
please dont
Low price hotel with high quality
Very good hotel with good facilities
Overall everything was fine
Overall, had an excellent stay
Amazing experience
new, clean, comfortable
Waste hotel
Good value for money and located conveniently
Budget Hotel
The rooms are clean and neat
Good & reasonable stay
Comfortable stay
Best hotel with nice service
Wonderful stay in great Chennai
Very Good
Good and value for money
Good facilities and clean room
More modern than other hotels in price range
Decent and good hotel to stay
Stay at Raj park
Good gotel for short stay
My review of the stay
Nice commercial hotel
Good Hotel.
Need lot of improvement in food
Prime location & definitely recommendable
Nice Comfortable stay, Excellent service and good staff
Need inspiration? Check out other reviews for The Park Chennai written by travellers like you or read some tips on writing great reviews.
Frud app
Issue with room AC
Quick 12 hour stop
5 star rooms at cheaper rates
My new favorite hotel in Chennai
hotel owner was supportive
pride in terms of location & quality of service
Good enviroment
Nice hotel with limited budget
Decent stay with fantastic food
close to us consulate and visa biometric center
Really Nice Hotel.
Not bad but space constraint
Nice hotel to my convinience
A relaxing Break from the streets of Chennai
Hotel is not for stay at this price
Not recommend
Sunny R&R in Chennai
Good place to stay at reasonable price
My home away from home
A clean, comfortable hotel with excellent food.
great food
Awesome ... Trip
Yes
Good hotel and nice location
Good stay with nice rooms & good food
Beyong expectation
TOP NOTCH HOTEL, Great Hotel
I wish there was another option in MWC
Affordable stay
Superb staff, spa and food!
Good
Good stay, nice locality
hotel nice
Home away from home!!
Nice place to stay for weekend
Good Hotel Near T Nagar with Good food, Service!!!
Pride of India
Helpful staff arranging local transportation
An excellent hotel
All in all Good
Good stay value formoney
Cleanliness is very poor & below average service
Cosy place to stay
Good food
Enjoyed my stay
Great helpful staff and Great Location
Very poor experience
Great one-night stay
Pathetic Hotel
Perfect stay for families
Nice place to stay for couple of days
Great option and value for money
Value For Money
Good appearance, facility and food
generally happy
GREAT
Best value for money, good location and facilities
Affordable decent hotel close to US Embassy
AJB Chennai 2 nights May 2013
Beach and temples.
Hotel looks good but rooms are not good
Pleasant staff and nice amenties
Llyods Guest House
Nice hotel with in city
Comfortable stay for the price offered
GOOD
Affordable and nice hotel
Good staff and not too good food
stay nice
Worst place & shabby rooms
Pleasant and comfortable stay
Staff is their strength
Decent hotel. Value for money paid.
Decent place to spend a night
review
Had a great time.
Good stay
Excellent Value for Money
Stay away from the wine
Over all V bad
Spacious rooms and polite staff
For mahalaya
Very good service. 15% less in price would help my pocket..
Good place to stay near to Guindy
Stay was comfortable with required facilities
Spacious rooms unlike other 3 star hotels
The Best Breakfast Buffet
A hotel with tasty food and good facilities
Very bad staff ugly hotel he shown me a good pics in here but given me a bad room full of mosquitoes smelly
stay hotelscom
Good hotel but still can improve
Perfect
Had a Good time
It's a quite a place to relax from business
perfect stay..just a bit too far from the airport
Good, can be improved
ok bad
nice place but approach is not so good
Had a comfortable stay
Very good hotel close to the airport
Nice hotel near the US Visa Consulate
Hotel look very class but uneducated receptionist.
nice hotel
We had good experience
extremely good
great business
Parking place was available
Good satisafaction
confirmation book
Nice place but with some problems
rating show
Comfortable hotel convenient for airport.
Tasty food and friendly staff
Placed in heart of city
usb one
breakfast could
really nice
nice
Good choice to stay in Chennai
additional bed
Good hotel in a prime location
Great stay experience
Great location and very poor service
Service and maintenance are very bad
Comfortable for transit stay
An overall nice hotel to stay at.
Good appearance but poor rooms
A pleasant stay
Not worthy for the money we are paying!
enjoy
??Great Hotel - Great Location -Bravo Ventana
old building
Nice hotel for staying and the service was very good
Budget friendly, clean and neat hotel
Poor service and management response
Needs to improve on room but good service
Good for a short stay
Club house Chennai
Absolutely fantastic stay, staff was very friendly
nice place
Definitely NOT a 5 star hotel they claim to be
Good place to stay
Hotel in town
Excellent serviced apartment
Good for a night stay without high expectations
Nice cozy place
Product Manager
Excellent and value for money
Good room service, worth the money
First stay at this hotel. Many cisits to India.
Good location, excellent staff.
Quality of food was good
Untidy and useless rooms
Great hotel. Great staff. GREAT FOOD.
No proper customer services
A basic hotel & not worth the money
Malles Manotaa - a good package
Very bad service but good breakfast
Good for short stay
Good hotel but food needs to improve
"Nice food hotel"
Was a pleasant stay, everything was super good !!!
worst cleanness in room, i never book again..
Terrible Hotel in a Bad Neighborhood
Biz trip
Very good hotel for the money paid
NICE PLACE AT A PRIME LOCATION
Good atmosphere with pleasant stay
Good one, value for money
Definitely one of the best hotel to stay
Don't miss the pool!
Amazing place to stay
Excellent budget hotel 10 min from Chennai airport
Overall good
Good hotel to stay in good location
Affordable Comfort
Poor service and food
Good for one night stay
"Comfort at Reasonable Prize"!!!!!
solid option
Good in service, kind and care
Good stay with all basic amenities
Terrific, I never go there..
Convenient location and good budget hotel
excellent hotel great staff
Crescent Inn Chennai India
Nice hotel for staying and tasty food
Comfortable stay & good hospitality
convenient and awesome
Nice hotel situated just besides the main road
Good stay with reasonable rate
A Great Hotel at A Great Budget.
Worst Service
Its good
Very good receiving and hosting totally very fine
Saticifactory hotel service!
Cheap room
Valet Parking & Vegan Food
Excellent stay
Good breakfast
Good Hotel ..
GREAT STAY
Excellent Stay!
Fantastic concept for night stay
Best hotel & awesome experience
Best place for families
Worst possible service received
Very satisfying experience
Great no Frills excellent room for business travel
Good but expensive hotel
not well
Great stay with courteous staff
Good location but need to improve on cleanliness
Old style 4 star property
Very uncooperative staff
Repeated Audio
Awesome appearance of exterior and interior
Right budget hotel
Its Good hotel
Good hospitality
Never stay in residency hotel
beautiful hotel
stay at Pride Banglore as a business stay is nice
Had a wonderful stay
Nice hotel to stay with friends and family
Good for quick business trip
stay hotel
Excellent
Royal Service
Full of bed bugs
Ok for low expenditure
Hotel is good
An average place to stay
Nice Feel
Can't expect much
Close to the largest mall in Chennai
Excellent stay and worth it
Good hotel with poor services
A graded
It was good experience with OYO rooms
Good hotel to stay with excellent service
Breakfast buffet style is appreciated
WAREX - stay at Mount Manor
No worth the rating shown in websites. Pricing is OK
Superb location is the only plus
Cute, simple
Radha Regent Best Motel for your buck!
Great hotel with excellent location in heart of the city
Rooms are well-maintained
Please try some other hotel
Average room stay
hotel sangeetha residency chennai
Great check in
Stay at Hotel Everest
Pleasant stay and comfortable
nice clean
Airport access
Good Stay, Good South Indian Food
Value for money with quite decent staff
Mr. Alliraj
Prime location and comfortable stay
Service to rooms are pretty slow
Great hotel
Peaceful stay & clean rooms
Budget stay at Chennai
Nice accommodation and facilities
Suited My Needs
excellent room with great service. well located
Worst
Amazing
bad smell
Nice stay
Good .. Worth the money
Overall good stay with clean rooms
Nice place to stay but carry your own breakfast
disastar
average amabiance
Homely villa
Good value in Chennai
Staff was very friendly and helpful
All basic amenities were provided
Overall worst experience
good food
i will come back to stay
Not good in any point of view
Check-in time issue & poor AC
Good quality food and convenient location
Good Place to stay
This hotel is good for pubbing only
Recommend to stay somewhere else
fabulous helpful
er
Great hotel not far from the airport
Reception is not good
Good atmosphere, food and drinks not available
Not worth for money
Very Ghostly Place(VGP)
Worst 'Hotel'. Should be renamed Lodge!!
Great location but facilities not as per expectation
Good hotel with comfortable stay
Calm hotel with all facilities, friendly staff
Budget hotel for Business people
Good!!!
a 5 star deserving hotel
Good services and but not up to the level
Good location and perfect stay
Good experience and value for money
Clean, Comfort and Convenient
Cleanliness not maintained
Pleasing staff and convenient Hotel
Good hotel in Chennai
Great place to stay
It's a fine  experience
Overnight stay for airport connection
Very poor service
Nice hotel to stay at shopping area
Great location, decent rooms, quite functional especially for a business trip!
comfortable and conveniently situated
Had a good stay!!
Decent for lodging and food
Average hotel experience and rooms are small
Very comfortable stay, very courteous staff
Beatifull Moments with my family
superb experience worth the money
good one
Nice hotel and worth for money
Nice hotel and friendly staff
Cordial staff & clean rooms
Excellent location & great value for money
AVERAGE
poor.
Awesome hotel with good service
Overall nice experience
The hotel is good, the food not so good
Location
great experience
OK
Overall fine stay
room rate
Good place.. would definitely recommend !
Great Service! :)
Nice Hotel with Amazing Breakfast Spred
Hotel with good location
Overall good stay
Best hotel to stay, value for money
Average class experience
Calm and budget friendly place
Best hotel to stay at Chennai
Ideal for business stay
Wouldn't recommend for more than a day's stay
Worth the value
Sagar kumar
Peaceful ambiance with cottage rooms
Average service & cleanliness
goood
Not a good experience
Good Location, Bad Rooms
comfortable to stay
love stay
Great Stay at this hotel!!
Excellent service
peace park inn
Just for airport budget stay
Nice location & value for money
Recommended
Very nice hotel for a stay
Value for Money
A haven of comfort.
A budget hotel
Not worse it
use double
Hotel Review
Good and Satisfactory stay
Greenery all over
overall Good
Excellent location
Okay but improvements needed
The staff's response was on time. The hotel was located inside the city. The maintenance was not good at the hotel. The provided room was spacious. Regularly the room was not well maintained. The food facility was not provided. The activity was not a
Recommended if travelling for your US visa intervi
Family trip
Hotel was very good
Not worth staying
Good Location
Short drive to airport
reasonably price
It cannot be worse than this
Beautiful hotel in the city center
Royal stay experience
Good Hotel , very good food
Lovely clean place to stay peacefully
Very homely and good service
Awesome Experience at Elk hill
Negative Feedback
The room was spacious
Closed to the airport
poor standards
it was a horrible experiance
Average standard hotel
Good stay, courteous staff
Reasonable place but has a long way to go..
amnesty breakfast
a friendly place close to the chaos of the street
Awesome service provided
Good hotel for stay but not a good location
Worst experience
Just forget the location and enjoy your stay
Had basic amenities and food was okay
Average Room
Old Rooms. Need renovation
Good location and goos service
Nice hotel. But needs a lot of improvement.
Bingo
The room is good and the service is also good
Rajesh Ashtekar
best audience
Rooms well-maintained and helpful staff
A perfect stay
Great Hotel and you forgot that you are in India
Not very good hotel
A recommended stay for family
Not great but more than okay
facility modern
Typical boring without any charm
Convenient and good location
No value for money
Worst Experience, won't prefer this anymore
Not good
Nice hotel to stay in the vital place
Great Service
Best place to stay
bad staff
Amazing place with very courteous staff
Best hotel for the corporate meeting
Pleasant Stay
That hotel was very nice
The Best serviced apartment in chennai
Hotel is at prime location
Clean and value for money hotel
Very good.
Small room size & bad service
The best place to stay when you are in Chennai.
Clean rooms, good food at the hotel restaurant
Hotel is fine
like food
Hotel not upto the mark
Shabby and poorly maintained
Greatest hotel in Chennai
Good service and nice breakfast
Decent place with good transport options
dated ....
convenient location
Good Location, Average Hotel, Bad Breakfast
3 star hotel with 5 star charges
Clean and tidy hotel
Best hotel to stay
always exact
Very good and comfortable
Excellent & nice
Great and big hotel with good services
Very Good Hotel in T Nagar
Very difficult to locate hotel
need improve
Wonderful and effortless stay
No transparency
OK location
Very good hotel
Joseph
Located in the heart of the city
Very well placed & good clean hotel
No SPA service
Because on website mention got SPA
Very Good Experience
Hotel review
JUST OK NO A VALUE TO PRICE
Friendly staff with prompt service, clean room
Impressive service and tasty food
Good Hotel
Great stay with good staff
Nice hotel in the heart of the city
Pretty Good
PERFECT HOTEL
nothing complain
satisfied
Enjoyed our stay
Good location but Very old facilities
nice hotel close to the shoping and temple
Worst experience ever
nice multi
Poor experience
clean great
Excellent location and awesome stay
Room allotted to me was neat
good
Was a nice place to stay
Location is very good near T.Nagar
Activity was not organized
Very expensive for the room they offered
Excellent hotel with delicious foods
average
Not value for money
Not up-to to the mark
Awesome stay
My stay at hotel pandyain
Pleasant and convenient stay
Helpful staff and great service
1.11111111111111E+056
A good deal
nice hotel with costly add ons
Its pleasant stay .. Just room service upsets me.
Disappointing Stay
Nothing much spacial
Not recommendable
Perfect I would recoup for to every one I know
Convenient for US Consulate visits
Very good hotel in Chennai
It was a pleasant stay
Value for money Hotel
High Quality Hotel with Strong Service
Worst behaviour
Good Stay - opt for the executive
Located well; maintained well, good food
Fantastic Hotel - opulence at its best
Katti-Ma
Nice place to enjoy with friends for a weekend
Average experience
nice room for recharge
A good and beautiful hotel
Decent hotel for short stay
Nice accommodation with excellent hospitality
A decent hotel
Good place to stay, value for money
Best stay in GST Road
A good place to stay
Good location at good price
Good hospitality and value for money
make it more convenient
5 star experience
Decent place
Just Lovely!
Will rethink on staying here.
Room maintenance and service is very good.
Akash
Grt Location!
Lovely hotel
Helpful front desk staff
Cosy experience and good for quick freshen up
Lotels serviced apartments is a calm place to stay
Good facilities & spacious room
stay was very good..staff was very courteous
Very poor AC and service
Great location and good services
Budget experience
Not satisfied & poor housekeeping
Good value
ambica empire review
Great Food & Good Hospitality
good**********************************************
overall stay
Nice location and clean room
service is good
Food tasted awful
Need to Improve on Customer Friendliness
Very good and clean
Excellent location & value for money
Nice and comfortable stay
Affordable hotel near to Airport
Great location
Nice hotel and staff
Not worth a try
Loved it
Decent place to stay away from home
room clean

In [ ]:
df

        Id                      Hotel_name  ... Rating Review_Title_Missed
0        0                      Park Hyatt  ...   80.0                   0
1        1                  Hilton Chennai  ...  100.0                   0
2        2               The Royal Regency  ...   71.0                   0
3        3                          Rivera  ...   86.0                   0
4        4                      Park Hyatt  ...   86.0                   0
...    ...                             ...  ...    ...                 ...
2346  2346           Hyatt Regency Chennai  ...   80.0                   1
2347  2347                   New Woodlands  ...   71.0                   0
2348  2348               Samudra Residency  ...  100.0                   0
2349  2349           The Residency Chennai  ...   80.0                   0
2350  2350  Cloud Nine Serviced Apartments  ...   71.0                   0

[2351 rows x 6 columns]

Мы заменили наны довольно-таки неплохим образом

Теперь почистим заголовок отзыва:

In [ ]:
df['Review_Title'] = df['Review_Title'].apply(clean_sent)

In [ ]:
df_test['Review_Title'] = df_test['Review_Title'].apply(clean_sent)

In [ ]:
df['Review_Title'] = df['Review_Title'].apply(lambda sentence: ' '.join([word for word in sentence.split() if word not in sw_eng]))

In [ ]:
df_test['Review_Title'] = df_test['Review_Title'].apply(lambda sentence: ' '.join([word for word in sentence.split() if word not in sw_eng]))

In [ ]:
df['Review_Title']

0                               refuge chennai
1                               hilton chennai
2       worth rating shown websites pricing ok
3                                    good stay
4                            needs improvement
                         ...
2346                        impressive service
2347                              homely villa
2348             nice accommodation facilities
2349    residency good centrally located hotel
2350                homely stay comfort luxury
Name: Review_Title, Length: 2351, dtype: object

In [ ]:
df['Review_Title'] = df['Review_Title'].apply(lambda sentence: ' '.join([spell(word) for word in sentence.split()]))

In [ ]:
df_test['Review_Title'] = df_test['Review_Title'].apply(lambda sentence: ' '.join([spell(word) for word in sentence.split()]))

In [ ]:
df['Review_Title'] = df['Review_Title'].apply(my_lemmatizer)

In [ ]:
df_test['Review_Title'] = df_test['Review_Title'].apply(my_lemmatizer)

In [ ]:
df['Review_Title']

0                              refuge chennai
1                              hilton chennai
2          worth rating show website price ok
3                                   good stay
4                            need improvement
                        ...
2346                       impressive service
2347                               home villa
2348              nice accommodation facility
2349    residency good centrally locate hotel
2350                 home stay comfort luxury
Name: Review_Title, Length: 2351, dtype: object

Применим TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
(df['Review_Text'] + ' ' + df['Review_Title'])[1]

'comfortable felt safe staff helpful respectful breakfast offer wide choice charter every palate start early finish late hilton chennai'

In [ ]:
foo = tfidf.fit_transform((df['Review_Text'] + ' ' + df['Review_Title']))

In [ ]:
df = df.join(pd.DataFrame(data=foo.todense(), columns=tfidf.vocabulary_))

In [ ]:
foo = tfidf.fit_transform((df_test['Review_Text'] + ' ' + df_test['Review_Title']))

In [ ]:
df_test = df_test.join(pd.DataFrame(data=foo.todense(), columns=tfidf.vocabulary_))

In [ ]:
!ls /content/MyDrive/MyDrive/тексты/дз/negative-words.txt

 negative-words.txt  'sample submission.csv'   test.csv    Untitled0.ipynb
 positive-words.txt   SentiWordNet.txt	       train.csv

In [ ]:
with open('/content/MyDrive/MyDrive/тексты/дз/negative-words.txt', encoding='ISO-8859-1') as f:
    bad_words = f.read().split('\n')
    print(bad_words)

['2-faced', '2-faces', 'abnormal', 'abolish', 'abominable', 'abominably', 'abominate', 'abomination', 'abort', 'aborted', 'aborts', 'abrade', 'abrasive', 'abrupt', 'abruptly', 'abscond', 'absence', 'absent-minded', 'absentee', 'absurd', 'absurdity', 'absurdly', 'absurdness', 'abuse', 'abused', 'abuses', 'abusive', 'abysmal', 'abysmally', 'abyss', 'accidental', 'accost', 'accursed', 'accusation', 'accusations', 'accuse', 'accuses', 'accusing', 'accusingly', 'acerbate', 'acerbic', 'acerbically', 'ache', 'ached', 'aches', 'achey', 'aching', 'acrid', 'acridly', 'acridness', 'acrimonious', 'acrimoniously', 'acrimony', 'adamant', 'adamantly', 'addict', 'addicted', 'addicting', 'addicts', 'admonish', 'admonisher', 'admonishingly', 'admonishment', 'admonition', 'adulterate', 'adulterated', 'adulteration', 'adulterier', 'adversarial', 'adversary', 'adverse', 'adversity', 'afflict', 'affliction', 'afflictive', 'affront', 'afraid', 'aggravate', 'aggravating', 'aggravation', 'aggression', 'aggressive', 'aggressiveness', 'aggressor', 'aggrieve', 'aggrieved', 'aggrivation', 'aghast', 'agonies', 'agonize', 'agonizing', 'agonizingly', 'agony', 'aground', 'ail', 'ailing', 'ailment', 'aimless', 'alarm', 'alarmed', 'alarming', 'alarmingly', 'alienate', 'alienated', 'alienation', 'allegation', 'allegations', 'allege', 'allergic', 'allergies', 'allergy', 'aloof', 'altercation', 'ambiguity', 'ambiguous', 'ambivalence', 'ambivalent', 'ambush', 'amiss', 'amputate', 'anarchism', 'anarchist', 'anarchistic', 'anarchy', 'anemic', 'anger', 'angrily', 'angriness', 'angry', 'anguish', 'animosity', 'annihilate', 'annihilation', 'annoy', 'annoyance', 'annoyances', 'annoyed', 'annoying', 'annoyingly', 'annoys', 'anomalous', 'anomaly', 'antagonism', 'antagonist', 'antagonistic', 'antagonize', 'anti-', 'anti-american', 'anti-israeli', 'anti-occupation', 'anti-proliferation', 'anti-semites', 'anti-social', 'anti-us', 'anti-white', 'antipathy', 'antiquated', 'antithetical', 'anxieties', 'anxiety', 'anxious', 'anxiously', 'anxiousness', 'apathetic', 'apathetically', 'apathy', 'apocalypse', 'apocalyptic', 'apologist', 'apologists', 'appal', 'appall', 'appalled', 'appalling', 'appallingly', 'apprehension', 'apprehensions', 'apprehensive', 'apprehensively', 'arbitrary', 'arcane', 'archaic', 'arduous', 'arduously', 'argumentative', 'arrogance', 'arrogant', 'arrogantly', 'ashamed', 'asinine', 'asininely', 'asinininity', 'askance', 'asperse', 'aspersion', 'aspersions', 'assail', 'assassin', 'assassinate', 'assault', 'assult', 'astray', 'asunder', 'atrocious', 'atrocities', 'atrocity', 'atrophy', 'attack', 'attacks', 'audacious', 'audaciously', 'audaciousness', 'audacity', 'audiciously', 'austere', 'authoritarian', 'autocrat', 'autocratic', 'avalanche', 'avarice', 'avaricious', 'avariciously', 'avenge', 'averse', 'aversion', 'aweful', 'awful', 'awfully', 'awfulness', 'awkward', 'awkwardness', 'ax', 'babble', 'back-logged', 'back-wood', 'back-woods', 'backache', 'backaches', 'backaching', 'backbite', 'backbiting', 'backward', 'backwardness', 'backwood', 'backwoods', 'bad', 'badly', 'baffle', 'baffled', 'bafflement', 'baffling', 'bait', 'balk', 'banal', 'banalize', 'bane', 'banish', 'banishment', 'bankrupt', 'barbarian', 'barbaric', 'barbarically', 'barbarity', 'barbarous', 'barbarously', 'barren', 'baseless', 'bash', 'bashed', 'bashful', 'bashing', 'bastard', 'bastards', 'battered', 'battering', 'batty', 'bearish', 'beastly', 'bedlam', 'bedlamite', 'befoul', 'beg', 'beggar', 'beggarly', 'begging', 'beguile', 'belabor', 'belated', 'beleaguer', 'belie', 'belittle', 'belittled', 'belittling', 'bellicose', 'belligerence', 'belligerent', 'belligerently', 'bemoan', 'bemoaning', 'bemused', 'bent', 'berate', 'bereave', 'bereavement', 'bereft', 'berserk', 'beseech', 'beset', 'besiege', 'besmirch', 'bestial', 'betray', 'betrayal', 'betrayals', 'betrayer', 'betraying', 'betrays', 'bewail', 'beware', 'bewilder', 'bewildered', 'bewildering', 'bewilderingly', 'bewilderment', 'bewitch', 'bias', 'biased', 'biases', 'bicker', 'bickering', 'bid-rigging', 'bigotries', 'bigotry', 'bitch', 'bitchy', 'biting', 'bitingly', 'bitter', 'bitterly', 'bitterness', 'bizarre', 'blab', 'blabber', 'blackmail', 'blah', 'blame', 'blameworthy', 'bland', 'blandish', 'blaspheme', 'blasphemous', 'blasphemy', 'blasted', 'blatant', 'blatantly', 'blather', 'bleak', 'bleakly', 'bleakness', 'bleed', 'bleeding', 'bleeds', 'blemish', 'blind', 'blinding', 'blindingly', 'blindside', 'blister', 'blistering', 'bloated', 'blockage', 'blockhead', 'bloodshed', 'bloodthirsty', 'bloody', 'blotchy', 'blow', 'blunder', 'blundering', 'blunders', 'blunt', 'blur', 'bluring', 'blurred', 'blurring', 'blurry', 'blurs', 'blurt', 'boastful', 'boggle', 'bogus', 'boil', 'boiling', 'boisterous', 'bomb', 'bombard', 'bombardment', 'bombastic', 'bondage', 'bonkers', 'bore', 'bored', 'boredom', 'bores', 'boring', 'botch', 'bother', 'bothered', 'bothering', 'bothers', 'bothersome', 'bowdlerize', 'boycott', 'braggart', 'bragger', 'brainless', 'brainwash', 'brash', 'brashly', 'brashness', 'brat', 'bravado', 'brazen', 'brazenly', 'brazenness', 'breach', 'break', 'break-up', 'break-ups', 'breakdown', 'breaking', 'breaks', 'breakup', 'breakups', 'bribery', 'brimstone', 'bristle', 'brittle', 'broke', 'broken', 'broken-hearted', 'brood', 'browbeat', 'bruise', 'bruised', 'bruises', 'bruising', 'brusque', 'brutal', 'brutalising', 'brutalities', 'brutality', 'brutalize', 'brutalizing', 'brutally', 'brute', 'brutish', 'bs', 'buckle', 'bug', 'bugging', 'buggy', 'bugs', 'bulkier', 'bulkiness', 'bulky', 'bulkyness', 'bull****', 'bull----', 'bullies', 'bullshit', 'bullshyt', 'bully', 'bullying', 'bullyingly', 'bum', 'bump', 'bumped', 'bumping', 'bumpping', 'bumps', 'bumpy', 'bungle', 'bungler', 'bungling', 'bunk', 'burden', 'burdensome', 'burdensomely', 'burn', 'burned', 'burning', 'burns', 'bust', 'busts', 'busybody', 'butcher', 'butchery', 'buzzing', 'byzantine', 'cackle', 'calamities', 'calamitous', 'calamitously', 'calamity', 'callous', 'calumniate', 'calumniation', 'calumnies', 'calumnious', 'calumniously', 'calumny', 'cancer', 'cancerous', 'cannibal', 'cannibalize', 'capitulate', 'capricious', 'capriciously', 'capriciousness', 'capsize', 'careless', 'carelessness', 'caricature', 'carnage', 'carp', 'cartoonish', 'cash-strapped', 'castigate', 'castrated', 'casualty', 'cataclysm', 'cataclysmal', 'cataclysmic', 'cataclysmically', 'catastrophe', 'catastrophes', 'catastrophic', 'catastrophically', 'catastrophies', 'caustic', 'caustically', 'cautionary', 'cave', 'censure', 'chafe', 'chaff', 'chagrin', 'challenging', 'chaos', 'chaotic', 'chasten', 'chastise', 'chastisement', 'chatter', 'chatterbox', 'cheap', 'cheapen', 'cheaply', 'cheat', 'cheated', 'cheater', 'cheating', 'cheats', 'checkered', 'cheerless', 'cheesy', 'chide', 'childish', 'chill', 'chilly', 'chintzy', 'choke', 'choleric', 'choppy', 'chore', 'chronic', 'chunky', 'clamor', 'clamorous', 'clash', 'cliche', 'cliched', 'clique', 'clog', 'clogged', 'clogs', 'cloud', 'clouding', 'cloudy', 'clueless', 'clumsy', 'clunky', 'coarse', 'cocky', 'coerce', 'coercion', 'coercive', 'cold', 'coldly', 'collapse', 'collude', 'collusion', 'combative', 'combust', 'comical', 'commiserate', 'commonplace', 'commotion', 'commotions', 'complacent', 'complain', 'complained', 'complaining', 'complains', 'complaint', 'complaints', 'complex', 'complicated', 'complication', 'complicit', 'compulsion', 'compulsive', 'concede', 'conceded', 'conceit', 'conceited', 'concen', 'concens', 'concern', 'concerned', 'concerns', 'concession', 'concessions', 'condemn', 'condemnable', 'condemnation', 'condemned', 'condemns', 'condescend', 'condescending', 'condescendingly', 'condescension', 'confess', 'confession', 'confessions', 'confined', 'conflict', 'conflicted', 'conflicting', 'conflicts', 'confound', 'confounded', 'confounding', 'confront', 'confrontation', 'confrontational', 'confuse', 'confused', 'confuses', 'confusing', 'confusion', 'confusions', 'congested', 'congestion', 'cons', 'conscons', 'conservative', 'conspicuous', 'conspicuously', 'conspiracies', 'conspiracy', 'conspirator', 'conspiratorial', 'conspire', 'consternation', 'contagious', 'contaminate', 'contaminated', 'contaminates', 'contaminating', 'contamination', 'contempt', 'contemptible', 'contemptuous', 'contemptuously', 'contend', 'contention', 'contentious', 'contort', 'contortions', 'contradict', 'contradiction', 'contradictory', 'contrariness', 'contravene', 'contrive', 'contrived', 'controversial', 'controversy', 'convoluted', 'corrode', 'corrosion', 'corrosions', 'corrosive', 'corrupt', 'corrupted', 'corrupting', 'corruption', 'corrupts', 'corruptted', 'costlier', 'costly', 'counter-productive', 'counterproductive', 'coupists', 'covetous', 'coward', 'cowardly', 'crabby', 'crack', 'cracked', 'cracks', 'craftily', 'craftly', 'crafty', 'cramp', 'cramped', 'cramping', 'cranky', 'crap', 'crappy', 'craps', 'crash', 'crashed', 'crashes', 'crashing', 'crass', 'craven', 'cravenly', 'craze', 'crazily', 'craziness', 'crazy', 'creak', 'creaking', 'creaks', 'credulous', 'creep', 'creeping', 'creeps', 'creepy', 'crept', 'crime', 'criminal', 'cringe', 'cringed', 'cringes', 'cripple', 'crippled', 'cripples', 'crippling', 'crisis', 'critic', 'critical', 'criticism', 'criticisms', 'criticize', 'criticized', 'criticizing', 'critics', 'cronyism', 'crook', 'crooked', 'crooks', 'crowded', 'crowdedness', 'crude', 'cruel', 'crueler', 'cruelest', 'cruelly', 'cruelness', 'cruelties', 'cruelty', 'crumble', 'crumbling', 'crummy', 'crumple', 'crumpled', 'crumples', 'crush', 'crushed', 'crushing', 'cry', 'culpable', 'culprit', 'cumbersome', 'cunt', 'cunts', 'cuplrit', 'curse', 'cursed', 'curses', 'curt', 'cuss', 'cussed', 'cutthroat', 'cynical', 'cynicism', 'd*mn', 'damage', 'damaged', 'damages', 'damaging', 'damn', 'damnable', 'damnably', 'damnation', 'damned', 'damning', 'damper', 'danger', 'dangerous', 'dangerousness', 'dark', 'darken', 'darkened', 'darker', 'darkness', 'dastard', 'dastardly', 'daunt', 'daunting', 'dauntingly', 'dawdle', 'daze', 'dazed', 'dead', 'deadbeat', 'deadlock', 'deadly', 'deadweight', 'deaf', 'dearth', 'death', 'debacle', 'debase', 'debasement', 'debaser', 'debatable', 'debauch', 'debaucher', 'debauchery', 'debilitate', 'debilitating', 'debility', 'debt', 'debts', 'decadence', 'decadent', 'decay', 'decayed', 'deceit', 'deceitful', 'deceitfully', 'deceitfulness', 'deceive', 'deceiver', 'deceivers', 'deceiving', 'deception', 'deceptive', 'deceptively', 'declaim', 'decline', 'declines', 'declining', 'decrement', 'decrepit', 'decrepitude', 'decry', 'defamation', 'defamations', 'defamatory', 'defame', 'defect', 'defective', 'defects', 'defensive', 'defiance', 'defiant', 'defiantly', 'deficiencies', 'deficiency', 'deficient', 'defile', 'defiler', 'deform', 'deformed', 'defrauding', 'defunct', 'defy', 'degenerate', 'degenerately', 'degeneration', 'degradation', 'degrade', 'degrading', 'degradingly', 'dehumanization', 'dehumanize', 'deign', 'deject', 'dejected', 'dejectedly', 'dejection', 'delay', 'delayed', 'delaying', 'delays', 'delinquency', 'delinquent', 'delirious', 'delirium', 'delude', 'deluded', 'deluge', 'delusion', 'delusional', 'delusions', 'demean', 'demeaning', 'demise', 'demolish', 'demolisher', 'demon', 'demonic', 'demonize', 'demonized', 'demonizes', 'demonizing', 'demoralize', 'demoralizing', 'demoralizingly', 'denial', 'denied', 'denies', 'denigrate', 'denounce', 'dense', 'dent', 'dented', 'dents', 'denunciate', 'denunciation', 'denunciations', 'deny', 'denying', 'deplete', 'deplorable', 'deplorably', 'deplore', 'deploring', 'deploringly', 'deprave', 'depraved', 'depravedly', 'deprecate', 'depress', 'depressed', 'depressing', 'depressingly', 'depression', 'depressions', 'deprive', 'deprived', 'deride', 'derision', 'derisive', 'derisively', 'derisiveness', 'derogatory', 'desecrate', 'desert', 'desertion', 'desiccate', 'desiccated', 'desititute', 'desolate', 'desolately', 'desolation', 'despair', 'despairing', 'despairingly', 'desperate', 'desperately', 'desperation', 'despicable', 'despicably', 'despise', 'despised', 'despoil', 'despoiler', 'despondence', 'despondency', 'despondent', 'despondently', 'despot', 'despotic', 'despotism', 'destabilisation', 'destains', 'destitute', 'destitution', 'destroy', 'destroyer', 'destruction', 'destructive', 'desultory', 'deter', 'deteriorate', 'deteriorating', 'deterioration', 'deterrent', 'detest', 'detestable', 'detestably', 'detested', 'detesting', 'detests', 'detract', 'detracted', 'detracting', 'detraction', 'detracts', 'detriment', 'detrimental', 'devastate', 'devastated', 'devastates', 'devastating', 'devastatingly', 'devastation', 'deviate', 'deviation', 'devil', 'devilish', 'devilishly', 'devilment', 'devilry', 'devious', 'deviously', 'deviousness', 'devoid', 'diabolic', 'diabolical', 'diabolically', 'diametrically', 'diappointed', 'diatribe', 'diatribes', 'dick', 'dictator', 'dictatorial', 'die', 'die-hard', 'died', 'dies', 'difficult', 'difficulties', 'difficulty', 'diffidence', 'dilapidated', 'dilemma', 'dilly-dally', 'dim', 'dimmer', 'din', 'ding', 'dings', 'dinky', 'dire', 'direly', 'direness', 'dirt', 'dirtbag', 'dirtbags', 'dirts', 'dirty', 'disable', 'disabled', 'disaccord', 'disadvantage', 'disadvantaged', 'disadvantageous', 'disadvantages', 'disaffect', 'disaffected', 'disaffirm', 'disagree', 'disagreeable', 'disagreeably', 'disagreed', 'disagreeing', 'disagreement', 'disagrees', 'disallow', 'disapointed', 'disapointing', 'disapointment', 'disappoint', 'disappointed', 'disappointing', 'disappointingly', 'disappointment', 'disappointments', 'disappoints', 'disapprobation', 'disapproval', 'disapprove', 'disapproving', 'disarm', 'disarray', 'disaster', 'disasterous', 'disastrous', 'disastrously', 'disavow', 'disavowal', 'disbelief', 'disbelieve', 'disbeliever', 'disclaim', 'discombobulate', 'discomfit', 'discomfititure', 'discomfort', 'discompose', 'disconcert', 'disconcerted', 'disconcerting', 'disconcertingly', 'disconsolate', 'disconsolately', 'disconsolation', 'discontent', 'discontented', 'discontentedly', 'discontinued', 'discontinuity', 'discontinuous', 'discord', 'discordance', 'discordant', 'discountenance', 'discourage', 'discouragement', 'discouraging', 'discouragingly', 'discourteous', 'discourteously', 'discoutinous', 'discredit', 'discrepant', 'discriminate', 'discrimination', 'discriminatory', 'disdain', 'disdained', 'disdainful', 'disdainfully', 'disfavor', 'disgrace', 'disgraced', 'disgraceful', 'disgracefully', 'disgruntle', 'disgruntled', 'disgust', 'disgusted', 'disgustedly', 'disgustful', 'disgustfully', 'disgusting', 'disgustingly', 'dishearten', 'disheartening', 'dishearteningly', 'dishonest', 'dishonestly', 'dishonesty', 'dishonor', 'dishonorable', 'dishonorablely', 'disillusion', 'disillusioned', 'disillusionment', 'disillusions', 'disinclination', 'disinclined', 'disingenuous', 'disingenuously', 'disintegrate', 'disintegrated', 'disintegrates', 'disintegration', 'disinterest', 'disinterested', 'dislike', 'disliked', 'dislikes', 'disliking', 'dislocated', 'disloyal', 'disloyalty', 'dismal', 'dismally', 'dismalness', 'dismay', 'dismayed', 'dismaying', 'dismayingly', 'dismissive', 'dismissively', 'disobedience', 'disobedient', 'disobey', 'disoobedient', 'disorder', 'disordered', 'disorderly', 'disorganized', 'disorient', 'disoriented', 'disown', 'disparage', 'disparaging', 'disparagingly', 'dispensable', 'dispirit', 'dispirited', 'dispiritedly', 'dispiriting', 'displace', 'displaced', 'displease', 'displeased', 'displeasing', 'displeasure', 'disproportionate', 'disprove', 'disputable', 'dispute', 'disputed', 'disquiet', 'disquieting', 'disquietingly', 'disquietude', 'disregard', 'disregardful', 'disreputable', 'disrepute', 'disrespect', 'disrespectable', 'disrespectablity', 'disrespectful', 'disrespectfully', 'disrespectfulness', 'disrespecting', 'disrupt', 'disruption', 'disruptive', 'diss', 'dissapointed', 'dissappointed', 'dissappointing', 'dissatisfaction', 'dissatisfactory', 'dissatisfied', 'dissatisfies', 'dissatisfy', 'dissatisfying', 'dissed', 'dissemble', 'dissembler', 'dissension', 'dissent', 'dissenter', 'dissention', 'disservice', 'disses', 'dissidence', 'dissident', 'dissidents', 'dissing', 'dissocial', 'dissolute', 'dissolution', 'dissonance', 'dissonant', 'dissonantly', 'dissuade', 'dissuasive', 'distains', 'distaste', 'distasteful', 'distastefully', 'distort', 'distorted', 'distortion', 'distorts', 'distract', 'distracting', 'distraction', 'distraught', 'distraughtly', 'distraughtness', 'distress', 'distressed', 'distressing', 'distressingly', 'distrust', 'distrustful', 'distrusting', 'disturb', 'disturbance', 'disturbed', 'disturbing', 'disturbingly', 'disunity', 'disvalue', 'divergent', 'divisive', 'divisively', 'divisiveness', 'dizzing', 'dizzingly', 'dizzy', 'doddering', 'dodgey', 'dogged', 'doggedly', 'dogmatic', 'doldrums', 'domineer', 'domineering', 'donside', 'doom', 'doomed', 'doomsday', 'dope', 'doubt', 'doubtful', 'doubtfully', 'doubts', 'douchbag', 'douchebag', 'douchebags', 'downbeat', 'downcast', 'downer', 'downfall', 'downfallen', 'downgrade', 'downhearted', 'downheartedly', 'downhill', 'downside', 'downsides', 'downturn', 'downturns', 'drab', 'draconian', 'draconic', 'drag', 'dragged', 'dragging', 'dragoon', 'drags', 'drain', 'drained', 'draining', 'drains', 'drastic', 'drastically', 'drawback', 'drawbacks', 'dread', 'dreadful', 'dreadfully', 'dreadfulness', 'dreary', 'dripped', 'dripping', 'drippy', 'drips', 'drones', 'droop', 'droops', 'drop-out', 'drop-outs', 'dropout', 'dropouts', 'drought', 'drowning', 'drunk', 'drunkard', 'drunken', 'dubious', 'dubiously', 'dubitable', 'dud', 'dull', 'dullard', 'dumb', 'dumbfound', 'dump', 'dumped', 'dumping', 'dumps', 'dunce', 'dungeon', 'dungeons', 'dupe', 'dust', 'dusty', 'dwindling', 'dying', 'earsplitting', 'eccentric', 'eccentricity', 'effigy', 'effrontery', 'egocentric', 'egomania', 'egotism', 'egotistical', 'egotistically', 'egregious', 'egregiously', 'election-rigger', 'elimination', 'emaciated', 'emasculate', 'embarrass', 'embarrassing', 'embarrassingly', 'embarrassment', 'embattled', 'embroil', 'embroiled', 'embroilment', 'emergency', 'emphatic', 'emphatically', 'emptiness', 'encroach', 'encroachment', 'endanger', 'enemies', 'enemy', 'enervate', 'enfeeble', 'enflame', 'engulf', 'enjoin', 'enmity', 'enrage', 'enraged', 'enraging', 'enslave', 'entangle', 'entanglement', 'entrap', 'entrapment', 'envious', 'enviously', 'enviousness', 'epidemic', 'equivocal', 'erase', 'erode', 'erodes', 'erosion', 'err', 'errant', 'erratic', 'erratically', 'erroneous', 'erroneously', 'error', 'errors', 'eruptions', 'escapade', 'eschew', 'estranged', 'evade', 'evasion', 'evasive', 'evil', 'evildoer', 'evils', 'eviscerate', 'exacerbate', 'exagerate', 'exagerated', 'exagerates', 'exaggerate', 'exaggeration', 'exasperate', 'exasperated', 'exasperating', 'exasperatingly', 'exasperation', 'excessive', 'excessively', 'exclusion', 'excoriate', 'excruciating', 'excruciatingly', 'excuse', 'excuses', 'execrate', 'exhaust', 'exhausted', 'exhaustion', 'exhausts', 'exhorbitant', 'exhort', 'exile', 'exorbitant', 'exorbitantance', 'exorbitantly', 'expel', 'expensive', 'expire', 'expired', 'explode', 'exploit', 'exploitation', 'explosive', 'expropriate', 'expropriation', 'expulse', 'expunge', 'exterminate', 'extermination', 'extinguish', 'extort', 'extortion', 'extraneous', 'extravagance', 'extravagant', 'extravagantly', 'extremism', 'extremist', 'extremists', 'eyesore', 'f**k', 'fabricate', 'fabrication', 'facetious', 'facetiously', 'fail', 'failed', 'failing', 'fails', 'failure', 'failures', 'faint', 'fainthearted', 'faithless', 'fake', 'fall', 'fallacies', 'fallacious', 'fallaciously', 'fallaciousness', 'fallacy', 'fallen', 'falling', 'fallout', 'falls', 'false', 'falsehood', 'falsely', 'falsify', 'falter', 'faltered', 'famine', 'famished', 'fanatic', 'fanatical', 'fanatically', 'fanaticism', 'fanatics', 'fanciful', 'far-f

In [ ]:
with open('/content/MyDrive/MyDrive/тексты/дз/positive-words.txt', encoding='ISO-8859-1') as f:
    good_words = f.read().split('\n')
    print(good_words)

['a+', 'abound', 'abounds', 'abundance', 'abundant', 'accessable', 'accessible', 'acclaim', 'acclaimed', 'acclamation', 'accolade', 'accolades', 'accommodative', 'accomodative', 'accomplish', 'accomplished', 'accomplishment', 'accomplishments', 'accurate', 'accurately', 'achievable', 'achievement', 'achievements', 'achievible', 'acumen', 'adaptable', 'adaptive', 'adequate', 'adjustable', 'admirable', 'admirably', 'admiration', 'admire', 'admirer', 'admiring', 'admiringly', 'adorable', 'adore', 'adored', 'adorer', 'adoring', 'adoringly', 'adroit', 'adroitly', 'adulate', 'adulation', 'adulatory', 'advanced', 'advantage', 'advantageous', 'advantageously', 'advantages', 'adventuresome', 'adventurous', 'advocate', 'advocated', 'advocates', 'affability', 'affable', 'affably', 'affectation', 'affection', 'affectionate', 'affinity', 'affirm', 'affirmation', 'affirmative', 'affluence', 'affluent', 'afford', 'affordable', 'affordably', 'afordable', 'agile', 'agilely', 'agility', 'agreeable', 'agreeableness', 'agreeably', 'all-around', 'alluring', 'alluringly', 'altruistic', 'altruistically', 'amaze', 'amazed', 'amazement', 'amazes', 'amazing', 'amazingly', 'ambitious', 'ambitiously', 'ameliorate', 'amenable', 'amenity', 'amiability', 'amiabily', 'amiable', 'amicability', 'amicable', 'amicably', 'amity', 'ample', 'amply', 'amuse', 'amusing', 'amusingly', 'angel', 'angelic', 'apotheosis', 'appeal', 'appealing', 'applaud', 'appreciable', 'appreciate', 'appreciated', 'appreciates', 'appreciative', 'appreciatively', 'appropriate', 'approval', 'approve', 'ardent', 'ardently', 'ardor', 'articulate', 'aspiration', 'aspirations', 'aspire', 'assurance', 'assurances', 'assure', 'assuredly', 'assuring', 'astonish', 'astonished', 'astonishing', 'astonishingly', 'astonishment', 'astound', 'astounded', 'astounding', 'astoundingly', 'astutely', 'attentive', 'attraction', 'attractive', 'attractively', 'attune', 'audible', 'audibly', 'auspicious', 'authentic', 'authoritative', 'autonomous', 'available', 'aver', 'avid', 'avidly', 'award', 'awarded', 'awards', 'awe', 'awed', 'awesome', 'awesomely', 'awesomeness', 'awestruck', 'awsome', 'backbone', 'balanced', 'bargain', 'beauteous', 'beautiful', 'beautifullly', 'beautifully', 'beautify', 'beauty', 'beckon', 'beckoned', 'beckoning', 'beckons', 'believable', 'believeable', 'beloved', 'benefactor', 'beneficent', 'beneficial', 'beneficially', 'beneficiary', 'benefit', 'benefits', 'benevolence', 'benevolent', 'benifits', 'best', 'best-known', 'best-performing', 'best-selling', 'better', 'better-known', 'better-than-expected', 'beutifully', 'blameless', 'bless', 'blessing', 'bliss', 'blissful', 'blissfully', 'blithe', 'blockbuster', 'bloom', 'blossom', 'bolster', 'bonny', 'bonus', 'bonuses', 'boom', 'booming', 'boost', 'boundless', 'bountiful', 'brainiest', 'brainy', 'brand-new', 'brave', 'bravery', 'bravo', 'breakthrough', 'breakthroughs', 'breathlessness', 'breathtaking', 'breathtakingly', 'breeze', 'bright', 'brighten', 'brighter', 'brightest', 'brilliance', 'brilliances', 'brilliant', 'brilliantly', 'brisk', 'brotherly', 'bullish', 'buoyant', 'cajole', 'calm', 'calming', 'calmness', 'capability', 'capable', 'capably', 'captivate', 'captivating', 'carefree', 'cashback', 'cashbacks', 'catchy', 'celebrate', 'celebrated', 'celebration', 'celebratory', 'champ', 'champion', 'charisma', 'charismatic', 'charitable', 'charm', 'charming', 'charmingly', 'chaste', 'cheaper', 'cheapest', 'cheer', 'cheerful', 'cheery', 'cherish', 'cherished', 'cherub', 'chic', 'chivalrous', 'chivalry', 'civility', 'civilize', 'clarity', 'classic', 'classy', 'clean', 'cleaner', 'cleanest', 'cleanliness', 'cleanly', 'clear', 'clear-cut', 'cleared', 'clearer', 'clearly', 'clears', 'clever', 'cleverly', 'cohere', 'coherence', 'coherent', 'cohesive', 'colorful', 'comely', 'comfort', 'comfortable', 'comfortably', 'comforting', 'comfy', 'commend', 'commendable', 'commendably', 'commitment', 'commodious', 'compact', 'compactly', 'compassion', 'compassionate', 'compatible', 'competitive', 'complement', 'complementary', 'complemented', 'complements', 'compliant', 'compliment', 'complimentary', 'comprehensive', 'conciliate', 'conciliatory', 'concise', 'confidence', 'confident', 'congenial', 'congratulate', 'congratulation', 'congratulations', 'congratulatory', 'conscientious', 'considerate', 'consistent', 'consistently', 'constructive', 'consummate', 'contentment', 'continuity', 'contrasty', 'contribution', 'convenience', 'convenient', 'conveniently', 'convience', 'convienient', 'convient', 'convincing', 'convincingly', 'cool', 'coolest', 'cooperative', 'cooperatively', 'cornerstone', 'correct', 'correctly', 'cost-effective', 'cost-saving', 'counter-attack', 'counter-attacks', 'courage', 'courageous', 'courageously', 'courageousness', 'courteous', 'courtly', 'covenant', 'cozy', 'creative', 'credence', 'credible', 'crisp', 'crisper', 'cure', 'cure-all', 'cushy', 'cute', 'cuteness', 'danke', 'danken', 'daring', 'daringly', 'darling', 'dashing', 'dauntless', 'dawn', 'dazzle', 'dazzled', 'dazzling', 'dead-cheap', 'dead-on', 'decency', 'decent', 'decisive', 'decisiveness', 'dedicated', 'defeat', 'defeated', 'defeating', 'defeats', 'defender', 'deference', 'deft', 'deginified', 'delectable', 'delicacy', 'delicate', 'delicious', 'delight', 'delighted', 'delightful', 'delightfully', 'delightfulness', 'dependable', 'dependably', 'deservedly', 'deserving', 'desirable', 'desiring', 'desirous', 'destiny', 'detachable', 'devout', 'dexterous', 'dexterously', 'dextrous', 'dignified', 'dignify', 'dignity', 'diligence', 'diligent', 'diligently', 'diplomatic', 'dirt-cheap', 'distinction', 'distinctive', 'distinguished', 'diversified', 'divine', 'divinely', 'dominate', 'dominated', 'dominates', 'dote', 'dotingly', 'doubtless', 'dreamland', 'dumbfounded', 'dumbfounding', 'dummy-proof', 'durable', 'dynamic', 'eager', 'eagerly', 'eagerness', 'earnest', 'earnestly', 'earnestness', 'ease', 'eased', 'eases', 'easier', 'easiest', 'easiness', 'easing', 'easy', 'easy-to-use', 'easygoing', 'ebullience', 'ebullient', 'ebulliently', 'ecenomical', 'economical', 'ecstasies', 'ecstasy', 'ecstatic', 'ecstatically', 'edify', 'educated', 'effective', 'effectively', 'effectiveness', 'effectual', 'efficacious', 'efficient', 'efficiently', 'effortless', 'effortlessly', 'effusion', 'effusive', 'effusively', 'effusiveness', 'elan', 'elate', 'elated', 'elatedly', 'elation', 'electrify', 'elegance', 'elegant', 'elegantly', 'elevate', 'elite', 'eloquence', 'eloquent', 'eloquently', 'embolden', 'eminence', 'eminent', 'empathize', 'empathy', 'empower', 'empowerment', 'enchant', 'enchanted', 'enchanting', 'enchantingly', 'encourage', 'encouragement', 'encouraging', 'encouragingly', 'endear', 'endearing', 'endorse', 'endorsed', 'endorsement', 'endorses', 'endorsing', 'energetic', 'energize', 'energy-efficient', 'energy-saving', 'engaging', 'engrossing', 'enhance', 'enhanced', 'enhancement', 'enhances', 'enjoy', 'enjoyable', 'enjoyably', 'enjoyed', 'enjoying', 'enjoyment', 'enjoys', 'enlighten', 'enlightenment', 'enliven', 'ennoble', 'enough', 'enrapt', 'enrapture', 'enraptured', 'enrich', 'enrichment', 'enterprising', 'entertain', 'entertaining', 'entertains', 'enthral', 'enthrall', 'enthralled', 'enthuse', 'enthusiasm', 'enthusiast', 'enthusiastic', 'enthusiastically', 'entice', 'enticed', 'enticing', 'enticingly', 'entranced', 'entrancing', 'entrust', 'enviable', 'enviably', 'envious', 'enviously', 'enviousness', 'envy', 'equitable', 'ergonomical', 'err-free', 'erudite', 'ethical', 'eulogize', 'euphoria', 'euphoric', 'euphorically', 'evaluative', 'evenly', 'eventful', 'everlasting', 'evocative', 'exalt', 'exaltation', 'exalted', 'exaltedly', 'exalting', 'exaltingly', 'examplar', 'examplary', 'excallent', 'exceed', 'exceeded', 'exceeding', 'exceedingly', 'exceeds', 'excel', 'exceled', 'excelent', 'excellant', 'excelled', 'excellence', 'excellency', 'excellent', 'excellently', 'excels', 'exceptional', 'exceptionally', 'excite', 'excited', 'excitedly', 'excitedness', 'excitement', 'excites', 'exciting', 'excitingly', 'exellent', 'exemplar', 'exemplary', 'exhilarate', 'exhilarating', 'exhilaratingly', 'exhilaration', 'exonerate', 'expansive', 'expeditiously', 'expertly', 'exquisite', 'exquisitely', 'extol', 'extoll', 'extraordinarily', 'extraordinary', 'exuberance', 'exuberant', 'exuberantly', 'exult', 'exultant', 'exultation', 'exultingly', 'eye-catch', 'eye-catching', 'eyecatch', 'eyecatching', 'fabulous', 'fabulously', 'facilitate', 'fair', 'fairly', 'fairness', 'faith', 'faithful', 'faithfully', 'faithfulness', 'fame', 'famed', 'famous', 'famously', 'fancier', 'fancinating', 'fancy', 'fanfare', 'fans', 'fantastic', 'fantastically', 'fascinate', 'fascinating', 'fascinatingly', 'fascination', 'fashionable', 'fashionably', 'fast', 'fast-growing', 'fast-paced', 'faster', 'fastest', 'fastest-growing', 'faultless', 'fav', 'fave', 'favor', 'favorable', 'favored', 'favorite', 'favorited', 'favour', 'fearless', 'fearlessly', 'feasible', 'feasibly', 'feat', 'feature-rich', 'fecilitous', 'feisty', 'felicitate', 'felicitous', 'felicity', 'fertile', 'fervent', 'fervently', 'fervid', 'fervidly', 'fervor', 'festive', 'fidelity', 'fiery', 'fine', 'fine-looking', 'finely', 'finer', 'finest', 'firmer', 'first-class', 'first-in-class', 'first-rate', 'flashy', 'flatter', 'flattering', 'flatteringly', 'flawless', 'flawlessly', 'flexibility', 'flexible', 'flourish', 'flourishing', 'fluent', 'flutter', 'fond', 'fondly', 'fondness', 'foolproof', 'foremost', 'foresight', 'formidable', 'fortitude', 'fortuitous', 'fortuitously', 'fortunate', 'fortunately', 'fortune', 'fragrant', 'free', 'freed', 'freedom', 'freedoms', 'fresh', 'fresher', 'freshest', 'friendliness', 'friendly', 'frolic', 'frugal', 'fruitful', 'ftw', 'fulfillment', 'fun', 'futurestic', 'futuristic', 'gaiety', 'gaily', 'gain', 'gained', 'gainful', 'gainfully', 'gaining', 'gains', 'gallant', 'gallantly', 'galore', 'geekier', 'geeky', 'gem', 'gems', 'generosity', 'generous', 'generously', 'genial', 'genius', 'gentle', 'gentlest', 'genuine', 'gifted', 'glad', 'gladden', 'gladly', 'gladness', 'glamorous', 'glee', 'gleeful', 'gleefully', 'glimmer', 'glimmering', 'glisten', 'glistening', 'glitter', 'glitz', 'glorify', 'glorious', 'gloriously', 'glory', 'glow', 'glowing', 'glowingly', 'god-given', 'god-send', 'godlike', 'godsend', 'gold', 'golden', 'good', 'goodly', 'goodness', 'goodwill', 'goood', 'gooood', 'gorgeous', 'gorgeously', 'grace', 'graceful', 'gracefully', 'gracious', 'graciously', 'graciousness', 'grand', 'grandeur', 'grateful', 'gratefully', 'gratification', 'gratified', 'gratifies', 'gratify', 'gratifying', 'gratifyingly', 'gratitude', 'great', 'greatest', 'greatness', 'grin', 'groundbreaking', 'guarantee', 'guidance', 'guiltless', 'gumption', 'gush', 'gusto', 'gutsy', 'hail', 'halcyon', 'hale', 'hallmark', 'hallmarks', 'hallowed', 'handier', 'handily', 'hands-down', 'handsome', 'handsomely', 'handy', 'happier', 'happily', 'happiness', 'happy', 'hard-working', 'hardier', 'hardy', 'harmless', 'harmonious', 'harmoniously', 'harmonize', 'harmony', 'headway', 'heal', 'healthful', 'healthy', 'hearten', 'heartening', 'heartfelt', 'heartily', 'heartwarming', 'heaven', 'heavenly', 'helped', 'helpful', 'helping', 'hero', 'heroic', 'heroically', 'heroine', 'heroize', 'heros', 'high-quality', 'high-spirited', 'hilarious', 'holy', 'homage', 'honest', 'honesty', 'honor', 'honorable', 'honored', 'honoring', 'hooray', 'hopeful', 'hospitable', 'hot', 'hotcake', 'hotcakes', 'hottest', 'hug', 'humane', 'humble', 'humility', 'humor', 'humorous', 'humorously', 'humour', 'humourous', 'ideal', 'idealize', 'ideally', 'idol', 'idolize', 'idolized', 'idyllic', 'illuminate', 'illuminati', 'illuminating', 'illumine', 'illustrious', 'ilu', 'imaculate', 'imaginative', 'immaculate', 'immaculately', 'immense', 'impartial', 'impartiality', 'impartially', 'impassioned', 'impeccable', 'impeccably', 'important', 'impress', 'impressed', 'impresses', 'impressive', 'impressively', 'impressiveness', 'improve', 'improved', 'improvement', 'improvements', 'improves', 'improving', 'incredible', 'incredibly', 'indebted', 'individualized', 'indulgence', 'indulgent', 'industrious', 'inestimable', 'inestimably', 'inexpensive', 'infallibility', 'infallible', 'infallibly', 'influential', 'ingenious', 'ingeniously', 'ingenuity', 'ingenuous', 'ingenuously', 'innocuous', 'innovation', 'innovative', 'inpressed', 'insightful', 'insightfully', 'inspiration', 'inspirational', 'inspire', 'inspiring', 'instantly', 'instructive', 'instrumental', 'integral', 'integrated', 'intelligence', 'intelligent', 'intelligible', 'interesting', 'interests', 'intimacy', 'intimate', 'intricate', 'intrigue', 'intriguing', 'intriguingly', 'intuitive', 'invaluable', 'invaluablely', 'inventive', 'invigorate', 'invigorating', 'invincibility', 'invincible', 'inviolable', 'inviolate', 'invulnerable', 'irreplaceable', 'irreproachable', 'irresistible', 'irresistibly', 'issue-free', 'jaw-droping', 'jaw-dropping', 'jollify', 'jolly', 'jovial', 'joy', 'joyful', 'joyfully', 'joyous', 'joyously', 'jubilant', 'jubilantly', 'jubilate', 'jubilation', 'jubiliant', 'judicious', 'justly', 'keen', 'keenly', 'keenness', 'kid-friendly', 'kindliness', 'kindly', 'kindness', 'knowledgeable', 'kudos', 'large-capacity', 'laud', 'laudable', 'laudably', 'lavish', 'lavishly', 'law-abiding', 'lawful', 'lawfully', 'lead', 'leading', 'leads', 'lean', 'led', 'legendary', 'leverage', 'levity', 'liberate', 'liberation', 'liberty', 'lifesaver', 'light-hearted', 'lighter', 'likable', 'like', 'liked', 'likes', 'liking', 'lionhearted', 'lively', 'logical', 'long-lasting', 'lovable', 'lovably', 'love', 'loved', 'loveliness', 'lovely', 'lover', 'loves', 'loving', 'low-cost', 'low-price', 'low-priced', 'low-risk', 'lower-priced', 'loyal', 'loyalty', 'lucid', 'lucidly', 'luck', 'luckier', 'luckiest', 'luckiness', 'lucky', 'lucrative', 'luminous', 'lush', 'luster', 'lustrous', 'luxuriant', 'luxuriate', 'luxurious', 'luxuriously', 'luxury', 'lyrical', 'magic', 'magical', 'magnanimous', 'magnanimously', 'magnificence', 'magnificent', 'magnificently', 'majestic', 'majesty', 'manageable', 'maneuverable', 'marvel', 'marveled', 'marvelled', 'marvellous', 'marvelous', 'marvelously', 'marvelousness', 'marvels', 'master', 'masterful', 'masterfully', 'masterpiece', 'masterpieces', 'masters', 'mastery', 'matchless', 'mature', 'maturely', 'maturity', 'meaningful', 'memorable', 'merciful', 'mercifully', 'mercy', 'merit', 'meritorious', 'merrily', 'merriment', 'merriness', 'merry', 'mesmerize', 'mesmerized', 'mesmerizes', 'mesmerizing', 'mesmerizingly', 'meticulous', 'meticulously', 'mightily', 'mighty', 'mind-blowing', 'miracle', 'miracles', 'miraculous', 'miraculously', 'miraculousness', 'modern', 'modest', 'modesty', 'momentous', 'monumental', 'monumentally', 'morality', 'motivated', 'multi-purpose', 'navigable', 'neat', 'neatest', 'neatly', 'nice', 'nicely', 'nicer', 'nicest', 'nifty', 'nimble', 'noble', 'nobly', 'noiseless', 'non-violence', 'non-violent', 'notably', 'noteworthy', 'nourish', 'nourishing', 'nourishment', 'novelty', 'nurturing', 'oasis', 'obsession', 'obsessions', 'obtainable', 'openly', 'openness', 'optimal', 'optimism', 'optimistic', 'opulent', 'orderly', 'originality', 'outdo', 'outdone', 'outperform', 'outperformed', 'outperforming', 'outperforms', 'outshine', 'outshone', 'outsmart', 'outstanding', 'outstandingly', 'outstrip', 'outwit', 'ovation', 'overjoyed', 'overtake', 'overtaken', 'overtakes', 'overtaking', 'overtook', 'overture', 'pain-free', 'painless', 'painlessly', 'palatial', 'pamper', 'pampered', 'pamperedly', 'pamperedness', 'pampers', 'panoramic', 'paradise', 'paramount', 'pardon', 'passion', 'passionate', 'passionately', 'patience', 'patient', 'patiently', 'patriot', 'patriotic', 'peace', 'peaceable', 'peaceful', 'peacefully', 'peacekeepers', 'peach', 'peerless', 'pep', 'pepped', 'pepping', 'peppy', 'peps', 'perfect', 'perfection', 'perfectly', 'permissible', 'perseverance', 'persevere', 'personages', 'personalized', 'phenomenal', 'phenomenally', 'picturesque', 'piety', 'pinnacle', 'playful', 'playfully', 'pleasant', 'pleasantly', 'pleased', 'pleases', 'pleasing', 'pleasingly', 'pleasurable', 'pleasurably', 'pleasure', 'plentiful', 'pluses', 'plush', 'plusses', 'poetic', 'poeticize', 'poignant', 'poise', 'poised', 'polished', 'polite', 'politeness', 'popular', 'portable', 'posh', 'positive', 'positively', 'positives', 'powerful', 'powerfully', 'praise', 'praiseworthy', 'praising', 'pre-eminent', 'precious', 'precise', 'precisely', 'preeminent', 'prefer', 'preferable', 'preferably', 'prefered', 'preferes', 'preferring', 'prefers', 'premier', 'prestige', 'prestigious', 'prettily', 'pretty', 'priceless', 'pride', 'principled', 'privilege', 'privileged', 'prize', 'proactive', 'problem-free', 'problem-solver', 'prodigious', 'prodigiously', 'prodigy', 'productive', 'productively', 'proficient', 'proficiently', 'profound', 'profoundly', 'profuse', 'profusion', 'progress', 'progressive', 'prolific', 'prominence', 'prominent', 'promise', 'promised', 'promises', 'promising', 'promoter', 'prompt', 'promptly', 'proper', 'properly', 'propitious', 'propitiously', 'pros', 'prosper', 'prosperity', 'prosperous', 'prospros', 'protect', 'protection', 'protective', 'proud', 'proven', 'proves', 'providence', 'proving', 'prowess', 'prudence', 'prudent', 'prudently', 'punctual', 'pure', 'purify', 'purposeful', 'quaint', 'qualified', 'qualify', 'quicker', 'quiet', 'quieter', 'radiance', 'radiant', 'rapid', 'rapport', 'rapt', 'rapture', 'raptureous', 'raptureously', 'rapturous', 'rapturously', 'rational', 'razor-sharp', 'reachable', 'readable', 'readily', 'ready', 'reaffirm', 'reaffirmation', 'realistic', 'realizable', 'reasonable', 'reasonably', 'reasoned', 'reassurance', 'reassure', 'receptive', 'reclaim', 'recomend', 'recommend', 'recommendation', 'recommendations', 'recommended', 'reconcile', 'reconciliation', 'record-setting', 'recover', 'recovery', 'rectification', 'rectify', 'rectifying', 'redeem', 'redeeming', 'redemption', 'refine', 'refined', 'refinement', 'reform', 'reformed', 'reforming', 'reforms', 'refresh', 'refreshed', 'refreshing', 'refund', 'refunded', 'regal', 'regally', 'regard', 'rejoice', 'rejoicing', 'rejoicingly', 'rejuvenate', 'rejuvenated', 'rejuvenating', 'relaxed', 'relent', 'reliable', 'reliably', 'relief', 'relish', 'remarkable', 'remarkably', 'remedy', 'remission', 'remunerate', 'renaissance', 'renewed', 'renown', 'renowned', 'replaceable', 'reputable', 'reputation', 'resilient', 'resolute', 'resound', 'resounding', 'resourceful', 'resourcefulness', 'respect', 'respectable', 'respectful', 'respectfully', 'respite', 'resplendent', 'responsibly', 'responsive', 'restful', 'restored', 'restructure', 'restructured', 'restructuring', 'retractable', 'revel', 'revelation', 'revere', 'reverence', 'reverent', 'reverently', 'revitalize', 'revival', 'revive', 'revives', 'revolutionary', 'revolutionize', 'revolutionized', 'revolutionizes', 'reward', 'rewarding', 'rewardingly', 'rich', 'richer', 'richly', 'richness', 'right', 'righten', 'righteous', 'righteously', 'righteousness', 'rightful', 'rightfully', 'rightly', 'rightness', 'risk-free', 'robust', 'rock-star', 'rock-stars', 'rockstar', 'rockstars', 'romantic', 'romantically', 'romanticize', 'roomier', 'roomy', 'rosy', 'safe', 'safely', 'sagacity', 'sagely', 'saint', 'saintliness', 'saintly', 'salutary', 'salute', 'sane', 'satisfactorily', 'satisfactory', 'satisfied', 'satisfies', 'satisfy', 'satisfying', 'satisified', 'saver', 'savings', 'savior', 'savvy', 'scenic', 'seamless', 'seasoned', 'secure', 'securely', 'selective', 'self-determination', 'self-respect', 'self-satisfaction', 'self-sufficiency', 'self-sufficient', 'sensation', 'sensational', 'sensationally', 'sensations', 'sensible', 'sensibly', 'sensitive', 'serene', 'serenity', 'sexy', 'sharp', 'sharper', 'sharpest', 'shimmerin

In [ ]:
def count_good_words(sentence):
    k = 0
    for word in sentence.split():
        if word in good_words:
            k += 1
    return k

def count_bad_words(sentence):
    k = 0
    for word in sentence.split():
        if word in bad_words:
            k += 1
    return k

Добавим признаки

In [ ]:
df['Number_Good_Words_Review_Text'] = df['Review_Text'].apply(count_good_words)

In [ ]:
df['Number_Bad_Words_Review_Text'] = df['Review_Text'].apply(count_bad_words)

In [ ]:
df['Number_Good_Words_Review_Title'] = df['Review_Title'].apply(count_good_words)

In [ ]:
df['Number_Bad_Words_Review_Title'] = df['Review_Title'].apply(count_bad_words)

In [ ]:
df_test['Number_Good_Words_Review_Text'] = df_test['Review_Text'].apply(count_good_words)

In [ ]:
df_test['Number_Bad_Words_Review_Text'] = df_test['Review_Text'].apply(count_bad_words)

In [ ]:
df_test['Number_Good_Words_Review_Title'] = df_test['Review_Title'].apply(count_good_words)

In [ ]:
df_test['Number_Bad_Words_Review_Title'] = df_test['Review_Title'].apply(count_bad_words)

In [ ]:
df_test

                              Hotel_name  ... Number_Bad_Words_Review_Title
0                        ITC Grand Chola  ...                             0
1                          Hotel Pandian  ...                             0
2     Oyo Rooms Guindy Olympia Tech Park  ...                             0
3                OYO Apartments Saidapet  ...                             0
4                  Ramada Chennai Egmore  ...                             0
...                                  ...  ...                           ...
2347                  Lemon Tree Chennai  ...                             0
2348  Oyo Rooms T Nagar Off Pondy Bazaar  ...                             1
2349             VGP Golden Beach Resort  ...                             0
2350                    The Park Chennai  ...                             1
2351                           Peace Inn  ...                             0

[2352 rows x 3727 columns]

в тесте есть странные колонки, но как их обработать я не придумал. колонки с именами: goodjjfjdjdjdjdjdkdkfkkfkkfkfkkfkkfkfkfkfkfknf	nfjjfkf	fjjfjkfknnf	jfjfjjfjjfjf	nfjfkkfkf	nfjfmfkfkfkfkfkr	ntktktkt	ktkktktjjtktkjtjjt	ktktktktktkmdkr	krkrkktkjdontnkd

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(labels='Rating', axis=1), df.Rating, test_size=0.3, random_state=42)

In [ ]:
X_train['Number_Good_Words_Review_Text'][X_train.Hotel_name == 'Rivera'].mean()

6.888888888888889

In [ ]:
mean_number_gw_hotel_train_text = dict(X_train.groupby(['Hotel_name'])['Number_Good_Words_Review_Text'].mean())
mean_number_gw_hotel_train_text

{'Aadithya': 8.666666666666666,
 'Abu sarovar portico ex Abu Palace': 5.25,
 'Accord Metropolitan': 4.288888888888889,
 'Akash Inn': 6.666666666666667,
 'Akshay Inn': 4.833333333333333,
 'Aloft Chennai Omr - It Expressway': 6.0,
 'Ambica Empire': 1.8,
 'Ammu Palace': 0.3333333333333333,
 'Ampa Skywalk': 2.6666666666666665,
 'Annsun Boutique': 7.25,
 'Apollo Serviced Apartments': 8.0,
 'Apple Residency': 8.0,
 'Aryaas': 3.0,
 'Asiana Place': 6.3,
 'Atchaya': 5.2,
 'Avnb Towers': 3.0,
 'BKR Convention Centre': 7.0,
 'BKR Grand': 4.333333333333333,
 'Beach Park Resort': 6.8,
 'Bell Hotel Chennai': 4.5,
 'Benzz Park': 2.6666666666666665,
 'Beverly Hotel': 6.428571428571429,
 'Bhimaas': 4.4,
 'Bluten by Traditions Inn': 5.2,
 'Brownstar Boutique Hotel': 3.4285714285714284,
 'Buhari Royale': 2.3333333333333335,
 'Chandra Park': 3.5,
 'Chennai Palace': 3.75,
 'Clarion Hotel President': 3.25,
 'Cloud Nine Serviced Apartments': 5.5,
 'Courtyard Chennai India': 6.625,
 'Crescent Hospitality Chennai': 2.0,
 'Crescent Park': 7.25,
 'Crystal Residency': 2.5,
 'Deccan Plaza': 3.9,
 'Dee Cee Manor': 4.0,
 'Dolphin Park': 5.2,
 'E Hotel': 3.5294117647058822,
 'Ekaana Cottages': 3.0,
 'Emarald': 3.4285714285714284,
 'Emerald Manor Chennai': 3.0,
 'Esthell': 6.333333333333333,
 'Everest': 4.2,
 'FabHotel Blossoms T Nagar': 5.5,
 'FabHotel Metro Manor Central Station': 4.75,
 'FabHotel Priyadarshini Park Mount Road': 2.909090909090909,
 'FabHotel Queensway T Nagar': 5.571428571428571,
 'Feathers- A Radha S': 2.0,
 'Fortel': 7.6,
 'Fortune Select Grand': 4.4,
 'Fortune Select Palms': 5.0,
 'Gemini Inn': 2.7,
 'Gemini Residency': 4.0,
 'Ginger Hotel': 4.285714285714286,
 'Glm Meridian': 1.5,
 'Global Residency Bed & Breakfast': 3.0,
 'Gokulam Park': 5.75,
 'Gokulam Park Sabari OMR': 4.5,
 'Golden Fruits Business Suites - T Nagar': 5.125,
 'Goldmine': 3.0,
 'Goutham Manor': 2.6,
 'Grand Chennai by GRT Hotels': 4.666666666666667,
 'Grand Palace': 5.25,
 'Grand Tiara by Purpletree': 0.0,
 'Grand Treat': 5.0,
 'Green Coconut Resort': 4.0,
 'Green Meadows': 4.5,
 'Green Park': 4.4,
 'Hablis Chennai': 2.25,
 'Hanu Reddy Residences Poes Garden': 5.333333333333333,
 'Hanu Reddy Residences Wallace Garden': 7.25,
 'Harrisons Chennai': 2.75,
 'Hilton Chennai': 4.357142857142857,
 'Holiday Inn Express Chennai Mahindra World City': 1.5,
 'Holiday Inn Express Chennai Old Mahabalipuram Road': 1.0,
 'Hotel Comfort': 3.0,
 'Hotel Grand Residence Porur': 3.3333333333333335,
 'Hotel Kensington': 8.0,
 'Hotel Pandian': 4.636363636363637,
 'Hotel Shelter': 4.5,
 'Hyatt Regency Chennai': 3.857142857142857,
 'ITC Grand Chola': 4.157894736842105,
 'JP Hotel': 1.5,
 'Just Guest House': 4.6,
 'Kek Accommodation': 5.5,
 'Keys Hotel Katti-Ma': 1.0,
 "King's Cross Residency": 5.75,
 'La Woods': 3.875,
 'Lake View Park': 3.3333333333333335,
 'Le Park Inn': 3.3333333333333335,
 'Le Royal M?ridien Chennai': 4.230769230769231,
 'Leisure Stays': 2.0,
 'Lemon Tree Chennai': 3.1714285714285713,
 'Lemon Tree Shimona': 3.6,
 'Lloyds Guest House': 6.5,
 'Lloyds Guest House - US Consulate': 3.0,
 'Lotels Hotel': 3.0,
 'MGM Eastwoods': 3.2222222222222223,
 'Mahalaya Residency': 2.0,
 'Mala Inn': 9.0,
 'Malles Manotaa': 4.666666666666667,
 'Mallika Reisidency': 1.8571428571428572,
 'Manickam Grand': 3.0,
 'Maple Tree': 3.5,
 'Marina Inn': 2.0,
 'Mars': 2.5,
 'Mars Classic': 1.8571428571428572,
 'Mars Deluxe': 0.0,
 'Marsan Lodge': 2.6666666666666665,
 'Maurya International': 6.333333333333333,
 'Melody': 2.0,
 'Metro Grand': 3.0,
 'Metropark - Vadapalani': 3.625,
 'Mount Heera': 2.375,
 'My Fortune Chennai': 4.909090909090909,
 'Nachiappa Park': 4.0,
 'Nakshatra Serviced Apartment - Siruseri': 3.0,
 'Nayagara': 3.5714285714285716,
 'New Park': 7.0,
 'New Woodlands': 6.153846153846154,
 'Novotel Chennai Sipcot': 3.0,
 'OMR Guest House': 2.6,
 'OYO Apartments T Nagar Pondy Bazaar': 7.0,
 'OYO Rooms Vadapalani Murugan Temple': 3.6666666666666665,
 'Opera Residency': 4.0,
 'Orange Inn Service Apartment (Manapakkam)': 3.25,
 'Orchid Inn Woods Road': 4.333333333333333,
 'Oriental Inn': 4.0,
 'Oyo Apartments Guduvanchery Srm University': 2.0,
 'Oyo Rooms Anna Arch Arumbakkam': 1.3333333333333333,
 'Oyo Rooms Chennai International Airport Road': 5.333333333333333,
 'Oyo Rooms Guindy Olympia Tech Park': 7.0,
 'Oyo Rooms Omr Sholinganallur': 3.6,
 'Oyo Rooms Royapettah': 5.0,
 'Oyo Rooms T Nagar Off Pondy Bazaar': 2.0,
 'Palace Lodge': 0.0,
 'Park Avenue': 3.75,
 'Park Hyatt': 3.5945945945945947,
 'Park Plaza Chennai': 5.0,
 'Peace Inn': 3.814814814814815,
 'Pearl International': 4.666666666666667,
 'Perfect Haven at Omr': 1.0,
 'Planet Mount': 7.5,
 'Pleasant Days': 6.0,
 'Pp Residency': 6.0,
 'Pratap Plaza': 3.4285714285714284,
 'Quality Inn Airport': 1.6666666666666667,
 'Quality Inn Sabari': 3.857142857142857,
 'Raaj Residency': 1.0,
 'Radha Regent': 5.0,
 'Radisson Blu GRT Chennai': 3.9285714285714284,
 'Radisson Chennai City Centre, India': 3.9705882352941178,
 'Raj Palace Hotel': 3.2857142857142856,
 'Raj Palace Sundar': 0.0,
 'Raj Park Chennai': 4.193548387096774,
 'Raj Residency': 2.6666666666666665,
 'Ramada Chennai Egmore': 5.0,
 'Redsun Serviced Apartments': 3.8,
 'Regency Royal Paris': 5.833333333333333,
 'Rivera': 6.888888888888889,
 'Royal Chennai Residency': 2.5,
 'Royal Plaza': 5.333333333333333,
 'Royal Star': 4.0,
 'Sai International': 2.0,
 'Saibala Grand': 3.0,
 'Sakithyan': 11.0,
 'Samco': 6.285714285714286,
 'Samudra Residency': 3.1666666666666665,
 'Sangeetha Residency': 6.857142857142857,
 'Sathyam Grand Resorts': 3.0,
 'Savera': 2.857142857142857,
 'Sea Shell Residency': 6.333333333333333,
 'Sea Shore Inn': 5.0,
 'Season 4 Guest House': 3.857142857142857,
 'Shan Royal': 4.888888888888889,
 'Sheraton Park Hotel & Towers': 4.5,
 'Shri Devi Park': 1.5,
 'Shylee Niwas Kodambakkam I': 6.0,
 'Somerset Greenways': 3.3333333333333335,
 "Sona's Inn": 3.0,
 'Sorrento Guest House': 8.5,
 'Southern Crest': 3.727272727272727,
 'Southern Residency': 7.0,
 'Sree Devi Niwas': 4.0,
 'Star City Serviced Apartments': 4.0,
 'Starcity Residence': 4.5,
 'Stay Easy Serviced Apartments Sholinganalur': 4.0,
 'Suriya International': 3.3636363636363638,
 'Surya Prakesh': 4.0,
 'Suvi Annexure': 2.25,
 'Taj Club House': 2.388888888888889,
 'Taj Coromandel': 5.888888888888889,
 'Taz Kamar Inn': 5.6,
 'Thaj Guest House': 5.0,
 'Thaj Regency': 7.6,
 'The Address': 5.0,
 'The Ambassador Pallava': 3.5,
 'The Centre Point': 7.0,
 'The Chamiers Park': 0.0,
 'The Chariot': 3.2,
 'The Checkers': 0.75,
 'The Gateway IT Expressway': 4.0,
 'The Iris': 3.2,
 'The Kings': 4.666666666666667,
 'The Leela Palace': 0.0,
 'The Lotus': 1.5,
 'The Lotus Serviced Apartments': 3.0,
 'The Mount Manor': 2.7,
 'The Park Chennai': 3.0,
 'The Pride': 5.0,
 'The Raintree': 3.923076923076923,
 "The Raintree, St. Mary's Road": 3.7142857142857144,
 'The Residency Chennai': 4.769230769230769,
 'The Residency Towers': 3.697674418604651,
 'The Royal Regency': 3.875,
 'The Spin': 4.75,
 'The Spring': 3.2,
 'The Vijay Park-Arumbakkam': 4.75,
 'The Westin Chennai Velachery': 4.75,
 'Thulashi Park': 5.666666666666667,
 'Treebo Angson': 4.333333333333333,
 'Treebo Elan': 3.0,
 'Treebo Grand Marena': 2.375,
 'Treebo Hive': 7.0,
 "Treebo J's Five Two Boutique": 4.6923076923076925,
 'Treebo Nestlay Casa': 2.3333333333333335,
 'Treebo Saravana Boutique Inn': 3.5,
 'Tri Sea Residency': 4.666666666666667,
 'Trident Chennai': 7.0,
 'Turyaa Chennai': 3.8333333333333335,
 'VGP Golden Beach Resort': 2.5714285714285716,
 'Vestin Park': 7.0,
 'Victoria': 5.666666666666667,
 'Zone By The Park Orr Chennai': 5.0,
 'ibis Chennai City Centre': 4.0,
 'ibis Chennai Sipcot': 4.375}

In [ ]:
mean_number_gw_hotel_test_text = dict(X_test.groupby(['Hotel_name'])['Number_Bad_Words_Review_Text'].mean())
mean_number_gw_hotel_test_text

{'Aadithya': 0.0,
 'Abu sarovar portico ex Abu Palace': 0.0,
 'Accord Metropolitan': 0.0625,
 'Akash Inn': 0.0,
 'Akshay Inn': 0.5,
 'Aloft Chennai Omr - It Expressway': 0.5,
 'Ambica Empire': 0.75,
 'Ampa Skywalk': 1.5,
 'Annsun Boutique': 0.0,
 'Apollo Serviced Apartments': 0.0,
 'Aryaas': 0.6666666666666666,
 'Asiana Place': 3.0,
 'Atchaya': 3.0,
 'Azeez Avenue': 0.5,
 'BKR Grand': 0.8,
 'Beach Park Resort': 0.0,
 'Bell Hotel Chennai': 0.5,
 'Beverly Hotel': 0.0,
 'Bhimaas': 0.5,
 'Bluten by Traditions Inn': 0.0,
 'Brownstar Boutique Hotel': 0.0,
 'Buhari Royale': 1.0,
 'Chandra Park': 1.6666666666666667,
 'Chennai Palace': 0.0,
 'Clarion Hotel President': 0.5,
 'Courtyard Chennai India': 0.0,
 'Crescent Park': 0.25,
 'Crystal Residency': 0.5,
 'Deccan Plaza': 0.0,
 'Dee Cee Manor': 0.0,
 'Dolphin Park': 1.75,
 'E Hotel': 0.5384615384615384,
 'Ekaana Cottages': 1.0,
 'Emarald': 0.6666666666666666,
 'Esthell': 0.3333333333333333,
 'Everest': 1.5,
 'FabHotel Blossoms T Nagar': 0.0,
 'FabHotel Metro Manor Central Station': 0.4,
 'FabHotel Priyadarshini Park Mount Road': 0.75,
 'FabHotel Queensway T Nagar': 0.0,
 'Fortel': 0.0,
 'Fortune Select Grand': 0.6666666666666666,
 'Fortune Select Palms': 0.0,
 'Gemini Inn': 0.0,
 'Ginger Hotel': 1.0,
 'Glm Meridian': 0.0,
 'Global Residency Bed & Breakfast': 0.0,
 'Gokulam Park': 1.0,
 'Golden Fruits Business Suites - T Nagar': 0.0,
 'Goldmine': 2.25,
 'Goutham Manor': 1.6666666666666667,
 'Grand Chennai by GRT Hotels': 1.0,
 'Grand Palace': 1.0,
 'Green Coconut Resort': 1.5,
 'Green Meadows': 0.0,
 'Green Park': 0.0,
 'Hablis Chennai': 4.0,
 'Hanu Reddy Residences Poes Garden': 0.5,
 'Hanu Reddy Residences Wallace Garden': 0.0,
 'Harrisons Chennai': 0.0,
 'Hilton Chennai': 1.0,
 'Holiday Inn Express Chennai Mahindra World City': 0.25,
 'Holiday Inn Express Chennai Old Mahabalipuram Road': 3.0,
 'Hotel Comfort': 0.0,
 'Hotel Grand Residence Porur': 0.4,
 'Hotel Kensington': 2.0,
 'Hotel Pandian': 0.6666666666666666,
 'Hotel Shelter': 0.5,
 'Hyatt Regency Chennai': 1.25,
 'ITC Grand Chola': 0.0,
 'JP Hotel': 1.0,
 'Just Guest House': 0.6666666666666666,
 'Kek Accommodation': 0.0,
 'Keys Hotel Katti-Ma': 2.0,
 "King's Cross Residency": 0.0,
 'La Woods': 0.3333333333333333,
 'Lake View Park': 2.0,
 'Le Park Inn': 0.0,
 'Le Royal M?ridien Chennai': 1.6666666666666667,
 'Lemon Tree Chennai': 0.6470588235294118,
 'Lemon Tree Shimona': 0.0,
 'Lloyds Guest House - US Consulate': 0.0,
 'Lotels Hotel': 0.0,
 'MGM Eastwoods': 0.3333333333333333,
 'Mahalaya Residency': 0.3333333333333333,
 'Malles Manotaa': 0.5,
 'Mallika Reisidency': 1.0,
 'Manickam Grand': 0.5,
 'Mars': 1.0,
 'Mars Classic': 2.625,
 'Mars Deluxe': 1.0,
 'Marsan Lodge': 0.0,
 'Maurya International': 1.6,
 'Metropark - Vadapalani': 0.6666666666666666,
 'Mount Heera': 3.5,
 'My Fortune Chennai': 0.0,
 'Nachiappa Park': 0.0,
 'Nayagara': 0.0,
 'New Woodlands': 0.42857142857142855,
 'OYO Apartments Saidapet': 2.0,
 'OYO Apartments T Nagar Pondy Bazaar': 1.0,
 'Opera Residency': 0.0,
 'Orange Inn Service Apartment (Manapakkam)': 0.0,
 'Orchid Inn Woods Road': 2.0,
 'Oyo Rooms Anna Arch Arumbakkam': 0.0,
 'Oyo Rooms Chennai International Airport Road': 0.0,
 'Oyo Rooms T Nagar Off Pondy Bazaar': 1.5,
 'Palace Lodge': 3.0,
 'Park Avenue': 0.0,
 'Park Hyatt': 0.5,
 'Park Plaza Chennai': 1.5,
 'Peace Inn': 0.9375,
 'Pearl International': 0.0,
 'Perfect Haven at Omr': 0.0,
 'Planet Mount': 0.0,
 'Pleasant Days': 0.0,
 'Pratap Plaza': 0.5,
 'Quality Inn Airport': 1.0,
 'Quality Inn Sabari': 1.0,
 'Radha Regent': 0.0,
 'Radisson Blu GRT Chennai': 0.2777777777777778,
 'Radisson Chennai City Centre, India': 0.5,
 'Raj Palace Hotel': 1.5714285714285714,
 'Raj Palace Sundar': 0.0,
 'Raj Park Chennai': 0.47619047619047616,
 'Raj Residency': 0.5,
 'Ramada Chennai Egmore': 2.0,
 'Redsun Serviced Apartments': 0.0,
 'Regency Royal Paris': 0.5,
 'Rivera': 0.0,
 'Royal Chennai Residency': 0.0,
 'Royal Plaza': 0.0,
 'Royal Star': 0.0,
 'Sai International': 0.0,
 'Sakithyan': 0.0,
 'Sakthi Grand': 1.0,
 'Samco': 1.0,
 'Samudra Residency': 1.0,
 'Sangeetha Residency': 0.4,
 'Sathyam Grand Resorts': 0.75,
 'Savera': 1.2380952380952381,
 'Sea Shell Residency': 0.0,
 'Sea Shore Inn': 0.0,
 'Season 4 Guest House': 0.3333333333333333,
 'Shan Royal': 3.0,
 'Shri Devi Park': 0.0,
 'Silver Park Guest House': 1.0,
 'Somerset Greenways': 0.2,
 'Sorrento Guest House': 2.0,
 'Southern Crest': 0.0,
 'Southern Residency': 0.6666666666666666,
 'Sree Devi Niwas': 2.0,
 'Star City Serviced Apartments': 0.0,
 'Suriya International': 0.5,
 'Surya Prakesh': 0.0,
 'Taj Club House': 1.5714285714285714,
 'Taj Coromandel': 1.75,
 'Taz Kamar Inn': 0.5,
 'Thaj Guest House': 0.5,
 'Thaj Regency': 0.0,
 'The Ambassador Pallava': 1.0,
 'The Centre Point': 2.5,
 'The Chariot': 0.8,
 'The Checkers': 0.0,
 'The Gateway IT Expressway': 0.0,
 'The Iris': 0.4,
 'The Kings': 0.0,
 'The Leela Palace': 0.0,
 'The Lotus  Sameera': 0.0,
 'The Mount Manor': 1.8,
 'The Park Chennai': 1.1904761904761905,
 'The Pride': 0.0,
 'The Raintree': 0.45454545454545453,
 "The Raintree, St. Mary's Road": 0.25,
 'The Residency Chennai': 0.9047619047619048,
 'The Residency Towers': 0.5,
 'The Royal Regency': 1.0,
 'The Spin': 0.3333333333333333,
 'The Spring': 2.0,
 'The Vijay Park-Arumbakkam': 0.7777777777777778,
 'Treebo Angson': 0.0,
 'Treebo Grand Marena': 1.0,
 'Treebo Hive': 0.0,
 "Treebo J's Five Two Boutique": 1.0,
 'Treebo Nestlay Casa': 0.5,
 'Tri Sea Residency': 0.5,
 'Trident Chennai': 0.25,
 'Turyaa Chennai': 1.25,
 'VGP Golden Beach Resort': 2.5,
 'Victoria': 0.0,
 'Yashwanth Residency': 2.0,
 'Zama Lodge': 0.5,
 'Zone By The Park Orr Chennai': 0.5,
 'ibis Chennai City Centre': 0.0,
 'ibis Chennai Sipcot': 0.0}

In [ ]:
mean_number_bw_hotel_train_text = dict(X_train.groupby(['Hotel_name'])['Number_Bad_Words_Review_Text'].mean())
mean_number_bw_hotel_train_text

{'Aadithya': 0.0,
 'Abu sarovar portico ex Abu Palace': 0.0,
 'Accord Metropolitan': 0.3111111111111111,
 'Akash Inn': 1.0,
 'Akshay Inn': 0.6666666666666666,
 'Aloft Chennai Omr - It Expressway': 0.5,
 'Ambica Empire': 1.4,
 'Ammu Palace': 2.6666666666666665,
 'Ampa Skywalk': 0.6666666666666666,
 'Annsun Boutique': 1.0,
 'Apollo Serviced Apartments': 0.0,
 'Apple Residency': 0.0,
 'Aryaas': 1.5,
 'Asiana Place': 0.4,
 'Atchaya': 0.2,
 'Avnb Towers': 0.4,
 'BKR Convention Centre': 1.0,
 'BKR Grand': 1.1111111111111112,
 'Beach Park Resort': 0.0,
 'Bell Hotel Chennai': 0.5,
 'Benzz Park': 3.0,
 'Beverly Hotel': 0.42857142857142855,
 'Bhimaas': 1.6,
 'Bluten by Traditions Inn': 0.8,
 'Brownstar Boutique Hotel': 0.0,
 'Buhari Royale': 1.3333333333333333,
 'Chandra Park': 2.3333333333333335,
 'Chennai Palace': 1.0,
 'Clarion Hotel President': 0.75,
 'Cloud Nine Serviced Apartments': 1.0,
 'Courtyard Chennai India': 0.625,
 'Crescent Hospitality Chennai': 4.0,
 'Crescent Park': 0.0,
 'Crystal Residency': 1.0,
 'Deccan Plaza': 1.4,
 'Dee Cee Manor': 2.0,
 'Dolphin Park': 0.6,
 'E Hotel': 0.5,
 'Ekaana Cottages': 1.0,
 'Emarald': 0.8571428571428571,
 'Emerald Manor Chennai': 0.0,
 'Esthell': 0.0,
 'Everest': 2.4,
 'FabHotel Blossoms T Nagar': 0.22727272727272727,
 'FabHotel Metro Manor Central Station': 0.75,
 'FabHotel Priyadarshini Park Mount Road': 1.1363636363636365,
 'FabHotel Queensway T Nagar': 1.0,
 'Feathers- A Radha S': 0.5,
 'Fortel': 0.6,
 'Fortune Select Grand': 0.2,
 'Fortune Select Palms': 1.5,
 'Gemini Inn': 1.9,
 'Gemini Residency': 1.0,
 'Ginger Hotel': 0.14285714285714285,
 'Glm Meridian': 1.125,
 'Global Residency Bed & Breakfast': 0.0,
 'Gokulam Park': 0.75,
 'Gokulam Park Sabari OMR': 0.5,
 'Golden Fruits Business Suites - T Nagar': 0.375,
 'Goldmine': 1.0,
 'Goutham Manor': 0.6,
 'Grand Chennai by GRT Hotels': 0.16666666666666666,
 'Grand Palace': 0.5,
 'Grand Tiara by Purpletree': 0.0,
 'Grand Treat': 1.0,
 'Green Coconut Resort': 0.0,
 'Green Meadows': 1.0,
 'Green Park': 0.4,
 'Hablis Chennai': 0.25,
 'Hanu Reddy Residences Poes Garden': 0.5,
 'Hanu Reddy Residences Wallace Garden': 0.25,
 'Harrisons Chennai': 0.5,
 'Hilton Chennai': 0.35714285714285715,
 'Holiday Inn Express Chennai Mahindra World City': 0.25,
 'Holiday Inn Express Chennai Old Mahabalipuram Road': 0.0,
 'Hotel Comfort': 0.6,
 'Hotel Grand Residence Porur': 0.3333333333333333,
 'Hotel Kensington': 0.0,
 'Hotel Pandian': 0.5454545454545454,
 'Hotel Shelter': 0.0,
 'Hyatt Regency Chennai': 0.8571428571428571,
 'ITC Grand Chola': 0.42105263157894735,
 'JP Hotel': 0.5,
 'Just Guest House': 0.4,
 'Kek Accommodation': 2.0,
 'Keys Hotel Katti-Ma': 1.6666666666666667,
 "King's Cross Residency": 1.0,
 'La Woods': 0.25,
 'Lake View Park': 1.8333333333333333,
 'Le Park Inn': 0.0,
 'Le Royal M?ridien Chennai': 0.6923076923076923,
 'Leisure Stays': 0.0,
 'Lemon Tree Chennai': 1.1428571428571428,
 'Lemon Tree Shimona': 0.0,
 'Lloyds Guest House': 0.0,
 'Lloyds Guest House - US Consulate': 0.0,
 'Lotels Hotel': 1.0,
 'MGM Eastwoods': 0.2222222222222222,
 'Mahalaya Residency': 0.75,
 'Mala Inn': 0.0,
 'Malles Manotaa': 0.16666666666666666,
 'Mallika Reisidency': 1.8571428571428572,
 'Manickam Grand': 1.9,
 'Maple Tree': 1.0,
 'Marina Inn': 1.5,
 'Mars': 1.5,
 'Mars Classic': 1.1428571428571428,
 'Mars Deluxe': 2.5,
 'Marsan Lodge': 0.3333333333333333,
 'Maurya International': 0.3333333333333333,
 'Melody': 0.0,
 'Metro Grand': 0.3333333333333333,
 'Metropark - Vadapalani': 0.25,
 'Mount Heera': 1.375,
 'My Fortune Chennai': 0.2727272727272727,
 'Nachiappa Park': 1.4,
 'Nakshatra Serviced Apartment - Siruseri': 0.0,
 'Nayagara': 0.7142857142857143,
 'New Park': 0.6666666666666666,
 'New Woodlands': 0.3076923076923077,
 'Novotel Chennai Sipcot': 1.0,
 'OMR Guest House': 1.0,
 'OYO Apartments T Nagar Pondy Bazaar': 1.0,
 'OYO Rooms Vadapalani Murugan Temple': 0.3333333333333333,
 'Opera Residency': 0.5,
 'Orange Inn Service Apartment (Manapakkam)': 2.0,
 'Orchid Inn Woods Road': 1.8333333333333333,
 'Oriental Inn': 0.5,
 'Oyo Apartments Guduvanchery Srm University': 0.0,
 'Oyo Rooms Anna Arch Arumbakkam': 0.3333333333333333,
 'Oyo Rooms Chennai International Airport Road': 1.0,
 'Oyo Rooms Guindy Olympia Tech Park': 0.25,
 'Oyo Rooms Omr Sholinganallur': 0.8,
 'Oyo Rooms Royapettah': 2.0,
 'Oyo Rooms T Nagar Off Pondy Bazaar': 0.0,
 'Palace Lodge': 1.0,
 'Park Avenue': 1.0,
 'Park Hyatt': 0.6486486486486487,
 'Park Plaza Chennai': 0.0,
 'Peace Inn': 0.6296296296296297,
 'Pearl International': 0.6666666666666666,
 'Perfect Haven at Omr': 0.0,
 'Planet Mount': 0.0,
 'Pleasant Days': 0.8,
 'Pp Residency': 0.0,
 'Pratap Plaza': 0.2857142857142857,
 'Quality Inn Airport': 0.3333333333333333,
 'Quality Inn Sabari': 0.5714285714285714,
 'Raaj Residency': 0.0,
 'Radha Regent': 0.6363636363636364,
 'Radisson Blu GRT Chennai': 0.5476190476190477,
 'Radisson Chennai City Centre, India': 0.5294117647058824,
 'Raj Palace Hotel': 1.0,
 'Raj Palace Sundar': 0.0,
 'Raj Park Chennai': 0.5483870967741935,
 'Raj Residency': 1.8888888888888888,
 'Ramada Chennai Egmore': 0.25,
 'Redsun Serviced Apartments': 0.0,
 'Regency Royal Paris': 0.5,
 'Rivera': 0.5555555555555556,
 'Royal Chennai Residency': 1.0,
 'Royal Plaza': 0.5,
 'Royal Star': 0.5,
 'Sai International': 0.0,
 'Saibala Grand': 2.0,
 'Sakithyan': 0.0,
 'Samco': 0.42857142857142855,
 'Samudra Residency': 0.5,
 'Sangeetha Residency': 0.2857142857142857,
 'Sathyam Grand Resorts': 1.0,
 'Savera': 0.7142857142857143,
 'Sea Shell Residency': 0.5,
 'Sea Shore Inn': 0.75,
 'Season 4 Guest House': 0.42857142857142855,
 'Shan Royal': 2.111111111111111,
 'Sheraton Park Hotel & Towers': 1.0,
 'Shri Devi Park': 0.0,
 'Shylee Niwas Kodambakkam I': 0.0,
 'Somerset Greenways': 0.5555555555555556,
 "Sona's Inn": 1.0,
 'Sorrento Guest House': 1.0,
 'Southern Crest': 0.36363636363636365,
 'Southern Residency': 0.6,
 'Sree Devi Niwas': 0.0,
 'Star City Serviced Apartments': 1.3333333333333333,
 'Starcity Residence': 0.5,
 'Stay Easy Serviced Apartments Sholinganalur': 1.0,
 'Suriya International': 1.2727272727272727,
 'Surya Prakesh': 0.6666666666666666,
 'Suvi Annexure': 0.75,
 'Taj Club House': 0.4444444444444444,
 'Taj Coromandel': 0.1111111111111111,
 'Taz Kamar Inn': 0.8,
 'Thaj Guest House': 0.0,
 'Thaj Regency': 0.0,
 'The Address': 0.0,
 'The Ambassador Pallava': 0.625,
 'The Centre Point': 0.25,
 'The Chamiers Park': 0.0,
 'The Chariot': 1.1333333333333333,
 'The Checkers': 1.75,
 'The Gateway IT Expressway': 1.0,
 'The Iris': 1.0,
 'The Kings': 0.6666666666666666,
 'The Leela Palace': 1.0,
 'The Lotus': 0.0,
 'The Lotus Serviced Apartments': 1.0,
 'The Mount Manor': 0.8,
 'The Park Chennai': 1.0612244897959184,
 'The Pride': 1.0,
 'The Raintree': 0.5769230769230769,
 "The Raintree, St. Mary's Road": 0.3333333333333333,
 'The Residency Chennai': 0.11538461538461539,
 'The Residency Towers': 0.37209302325581395,
 'The Royal Regency': 0.625,
 'The Spin': 0.0,
 'The Spring': 0.8,
 'The Vijay Park-Arumbakkam': 4.0,
 'The Westin Chennai Velachery': 1.0,
 'Thulashi Park': 2.0,
 'Treebo Angson': 0.3333333333333333,
 'Treebo Elan': 2.0,
 'Treebo Grand Marena': 0.875,
 'Treebo Hive': 0.4,
 "Treebo J's Five Two Boutique": 1.0,
 'Treebo Nestlay Casa': 0.3333333333333333,
 'Treebo Saravana Boutique Inn': 0.0,
 'Tri Sea Residency': 0.6666666666666666,
 'Trident Chennai': 0.3333333333333333,
 'Turyaa Chennai': 0.8333333333333334,
 'VGP Golden Beach Resort': 1.5714285714285714,
 'Vestin Park': 1.0,
 'Victoria': 0.6666666666666666,
 'Zone By The Park Orr Chennai': 1.0,
 'ibis Chennai City Centre': 0.0,
 'ibis Chennai Sipcot': 0.875}

In [ ]:
mean_number_bw_hotel_test_text = dict(X_test.groupby(['Hotel_name'])['Number_Bad_Words_Review_Text'].mean())
mean_number_bw_hotel_test_text

{'Aadithya': 0.0,
 'Abu sarovar portico ex Abu Palace': 0.0,
 'Accord Metropolitan': 0.0625,
 'Akash Inn': 0.0,
 'Akshay Inn': 0.5,
 'Aloft Chennai Omr - It Expressway': 0.5,
 'Ambica Empire': 0.75,
 'Ampa Skywalk': 1.5,
 'Annsun Boutique': 0.0,
 'Apollo Serviced Apartments': 0.0,
 'Aryaas': 0.6666666666666666,
 'Asiana Place': 3.0,
 'Atchaya': 3.0,
 'Azeez Avenue': 0.5,
 'BKR Grand': 0.8,
 'Beach Park Resort': 0.0,
 'Bell Hotel Chennai': 0.5,
 'Beverly Hotel': 0.0,
 'Bhimaas': 0.5,
 'Bluten by Traditions Inn': 0.0,
 'Brownstar Boutique Hotel': 0.0,
 'Buhari Royale': 1.0,
 'Chandra Park': 1.6666666666666667,
 'Chennai Palace': 0.0,
 'Clarion Hotel President': 0.5,
 'Courtyard Chennai India': 0.0,
 'Crescent Park': 0.25,
 'Crystal Residency': 0.5,
 'Deccan Plaza': 0.0,
 'Dee Cee Manor': 0.0,
 'Dolphin Park': 1.75,
 'E Hotel': 0.5384615384615384,
 'Ekaana Cottages': 1.0,
 'Emarald': 0.6666666666666666,
 'Esthell': 0.3333333333333333,
 'Everest': 1.5,
 'FabHotel Blossoms T Nagar': 0.0,
 'FabHotel Metro Manor Central Station': 0.4,
 'FabHotel Priyadarshini Park Mount Road': 0.75,
 'FabHotel Queensway T Nagar': 0.0,
 'Fortel': 0.0,
 'Fortune Select Grand': 0.6666666666666666,
 'Fortune Select Palms': 0.0,
 'Gemini Inn': 0.0,
 'Ginger Hotel': 1.0,
 'Glm Meridian': 0.0,
 'Global Residency Bed & Breakfast': 0.0,
 'Gokulam Park': 1.0,
 'Golden Fruits Business Suites - T Nagar': 0.0,
 'Goldmine': 2.25,
 'Goutham Manor': 1.6666666666666667,
 'Grand Chennai by GRT Hotels': 1.0,
 'Grand Palace': 1.0,
 'Green Coconut Resort': 1.5,
 'Green Meadows': 0.0,
 'Green Park': 0.0,
 'Hablis Chennai': 4.0,
 'Hanu Reddy Residences Poes Garden': 0.5,
 'Hanu Reddy Residences Wallace Garden': 0.0,
 'Harrisons Chennai': 0.0,
 'Hilton Chennai': 1.0,
 'Holiday Inn Express Chennai Mahindra World City': 0.25,
 'Holiday Inn Express Chennai Old Mahabalipuram Road': 3.0,
 'Hotel Comfort': 0.0,
 'Hotel Grand Residence Porur': 0.4,
 'Hotel Kensington': 2.0,
 'Hotel Pandian': 0.6666666666666666,
 'Hotel Shelter': 0.5,
 'Hyatt Regency Chennai': 1.25,
 'ITC Grand Chola': 0.0,
 'JP Hotel': 1.0,
 'Just Guest House': 0.6666666666666666,
 'Kek Accommodation': 0.0,
 'Keys Hotel Katti-Ma': 2.0,
 "King's Cross Residency": 0.0,
 'La Woods': 0.3333333333333333,
 'Lake View Park': 2.0,
 'Le Park Inn': 0.0,
 'Le Royal M?ridien Chennai': 1.6666666666666667,
 'Lemon Tree Chennai': 0.6470588235294118,
 'Lemon Tree Shimona': 0.0,
 'Lloyds Guest House - US Consulate': 0.0,
 'Lotels Hotel': 0.0,
 'MGM Eastwoods': 0.3333333333333333,
 'Mahalaya Residency': 0.3333333333333333,
 'Malles Manotaa': 0.5,
 'Mallika Reisidency': 1.0,
 'Manickam Grand': 0.5,
 'Mars': 1.0,
 'Mars Classic': 2.625,
 'Mars Deluxe': 1.0,
 'Marsan Lodge': 0.0,
 'Maurya International': 1.6,
 'Metropark - Vadapalani': 0.6666666666666666,
 'Mount Heera': 3.5,
 'My Fortune Chennai': 0.0,
 'Nachiappa Park': 0.0,
 'Nayagara': 0.0,
 'New Woodlands': 0.42857142857142855,
 'OYO Apartments Saidapet': 2.0,
 'OYO Apartments T Nagar Pondy Bazaar': 1.0,
 'Opera Residency': 0.0,
 'Orange Inn Service Apartment (Manapakkam)': 0.0,
 'Orchid Inn Woods Road': 2.0,
 'Oyo Rooms Anna Arch Arumbakkam': 0.0,
 'Oyo Rooms Chennai International Airport Road': 0.0,
 'Oyo Rooms T Nagar Off Pondy Bazaar': 1.5,
 'Palace Lodge': 3.0,
 'Park Avenue': 0.0,
 'Park Hyatt': 0.5,
 'Park Plaza Chennai': 1.5,
 'Peace Inn': 0.9375,
 'Pearl International': 0.0,
 'Perfect Haven at Omr': 0.0,
 'Planet Mount': 0.0,
 'Pleasant Days': 0.0,
 'Pratap Plaza': 0.5,
 'Quality Inn Airport': 1.0,
 'Quality Inn Sabari': 1.0,
 'Radha Regent': 0.0,
 'Radisson Blu GRT Chennai': 0.2777777777777778,
 'Radisson Chennai City Centre, India': 0.5,
 'Raj Palace Hotel': 1.5714285714285714,
 'Raj Palace Sundar': 0.0,
 'Raj Park Chennai': 0.47619047619047616,
 'Raj Residency': 0.5,
 'Ramada Chennai Egmore': 2.0,
 'Redsun Serviced Apartments': 0.0,
 'Regency Royal Paris': 0.5,
 'Rivera': 0.0,
 'Royal Chennai Residency': 0.0,
 'Royal Plaza': 0.0,
 'Royal Star': 0.0,
 'Sai International': 0.0,
 'Sakithyan': 0.0,
 'Sakthi Grand': 1.0,
 'Samco': 1.0,
 'Samudra Residency': 1.0,
 'Sangeetha Residency': 0.4,
 'Sathyam Grand Resorts': 0.75,
 'Savera': 1.2380952380952381,
 'Sea Shell Residency': 0.0,
 'Sea Shore Inn': 0.0,
 'Season 4 Guest House': 0.3333333333333333,
 'Shan Royal': 3.0,
 'Shri Devi Park': 0.0,
 'Silver Park Guest House': 1.0,
 'Somerset Greenways': 0.2,
 'Sorrento Guest House': 2.0,
 'Southern Crest': 0.0,
 'Southern Residency': 0.6666666666666666,
 'Sree Devi Niwas': 2.0,
 'Star City Serviced Apartments': 0.0,
 'Suriya International': 0.5,
 'Surya Prakesh': 0.0,
 'Taj Club House': 1.5714285714285714,
 'Taj Coromandel': 1.75,
 'Taz Kamar Inn': 0.5,
 'Thaj Guest House': 0.5,
 'Thaj Regency': 0.0,
 'The Ambassador Pallava': 1.0,
 'The Centre Point': 2.5,
 'The Chariot': 0.8,
 'The Checkers': 0.0,
 'The Gateway IT Expressway': 0.0,
 'The Iris': 0.4,
 'The Kings': 0.0,
 'The Leela Palace': 0.0,
 'The Lotus  Sameera': 0.0,
 'The Mount Manor': 1.8,
 'The Park Chennai': 1.1904761904761905,
 'The Pride': 0.0,
 'The Raintree': 0.45454545454545453,
 "The Raintree, St. Mary's Road": 0.25,
 'The Residency Chennai': 0.9047619047619048,
 'The Residency Towers': 0.5,
 'The Royal Regency': 1.0,
 'The Spin': 0.3333333333333333,
 'The Spring': 2.0,
 'The Vijay Park-Arumbakkam': 0.7777777777777778,
 'Treebo Angson': 0.0,
 'Treebo Grand Marena': 1.0,
 'Treebo Hive': 0.0,
 "Treebo J's Five Two Boutique": 1.0,
 'Treebo Nestlay Casa': 0.5,
 'Tri Sea Residency': 0.5,
 'Trident Chennai': 0.25,
 'Turyaa Chennai': 1.25,
 'VGP Golden Beach Resort': 2.5,
 'Victoria': 0.0,
 'Yashwanth Residency': 2.0,
 'Zama Lodge': 0.5,
 'Zone By The Park Orr Chennai': 0.5,
 'ibis Chennai City Centre': 0.0,
 'ibis Chennai Sipcot': 0.0}

Добавляем фичи среднее количество плохих и хороших слов по отелям в заголовке и тексте отзыва и применяем one hot encoding к именам отелей для X_train, X_test, df_test

In [ ]:
X_train['mean_number_good_words_hotel_text'] = X_train['Hotel_name'].apply(lambda hotel_name: mean_number_gw_hotel_train_text[hotel_name])

In [ ]:
X_train['mean_number_bad_words_hotel_text'] = X_train['Hotel_name'].apply(lambda hotel_name: mean_number_bw_hotel_train_text[hotel_name])

In [ ]:
X_test['mean_number_good_words_hotel_text'] = X_test['Hotel_name'].apply(lambda hotel_name: mean_number_gw_hotel_test_text[hotel_name])

In [ ]:
X_test['mean_number_bad_words_hotel_text'] = X_test['Hotel_name'].apply(lambda hotel_name: mean_number_bw_hotel_test_text[hotel_name])

In [ ]:
mean_number_gw_hotel_test_text = dict(df_test.groupby(['Hotel_name'])['Number_Good_Words_Review_Text'].mean())
mean_number_bw_hotel_test_text = dict(df_test.groupby(['Hotel_name'])['Number_Bad_Words_Review_Text'].mean())

In [ ]:
df_test['mean_number_bad_words_hotel_text'] = df_test['Hotel_name'].apply(lambda hotel_name: mean_number_bw_hotel_test_text[hotel_name])
df_test['mean_number_good_words_hotel_text'] = df_test['Hotel_name'].apply(lambda hotel_name: mean_number_gw_hotel_test_text[hotel_name])

In [ ]:
mean_number_gw_hotel_train_title = dict(X_train.groupby(['Hotel_name'])['Number_Good_Words_Review_Title'].mean())
mean_number_gw_hotel_test_title = dict(X_test.groupby(['Hotel_name'])['Number_Good_Words_Review_Title'].mean())
mean_number_bw_hotel_train_title = dict(X_train.groupby(['Hotel_name'])['Number_Bad_Words_Review_Title'].mean())
mean_number_bw_hotel_test_title = dict(X_test.groupby(['Hotel_name'])['Number_Bad_Words_Review_Title'].mean())

X_train['mean_number_good_words_hotel_title'] = X_train['Hotel_name'].apply(lambda hotel_name: mean_number_gw_hotel_train_title[hotel_name])
X_train['mean_number_bad_words_hotel_title'] = X_train['Hotel_name'].apply(lambda hotel_name: mean_number_bw_hotel_train_title[hotel_name])
X_test['mean_number_good_words_hotel_title'] = X_test['Hotel_name'].apply(lambda hotel_name: mean_number_gw_hotel_test_title[hotel_name])
X_test['mean_number_bad_words_hotel_title'] = X_test['Hotel_name'].apply(lambda hotel_name: mean_number_bw_hotel_test_title[hotel_name])

In [ ]:
mean_number_gw_hotel_test_title = dict(df_test.groupby(['Hotel_name'])['Number_Good_Words_Review_Title'].mean())
mean_number_bw_hotel_test_title = dict(df_test.groupby(['Hotel_name'])['Number_Bad_Words_Review_Title'].mean())

df_test['mean_number_bad_words_hotel_title'] = df_test['Hotel_name'].apply(lambda hotel_name: mean_number_bw_hotel_test_title[hotel_name])
df_test['mean_number_good_words_hotel_title'] = df_test['Hotel_name'].apply(lambda hotel_name: mean_number_gw_hotel_test_title[hotel_name])

In [ ]:
X_train = pd.get_dummies(X_train, columns = ['Hotel_name'])

In [ ]:
X_test = pd.get_dummies(X_test, columns = ['Hotel_name'])

In [ ]:
df_test = pd.get_dummies(df_test, columns = ['Hotel_name'])

In [ ]:
X_train

                     Review_Title  ... Hotel_name_ibis Chennai Sipcot
1503      perfect location u visa  ...                              0
1420                       normal  ...                              0
1763              good hotel stay  ...                              0
1356  great location good service  ...                              0
1117                    good stay  ...                              0
...                           ...  ...                            ...
1638             poor maintenance  ...                              0
1095             great experience  ...                              0
1130                 average stay  ...                              0
1294   poor resort please dont go  ...                              0
860                 hotel enpedia  ...                              0

[1645 rows x 3952 columns]

In [ ]:
X_test

                              Review_Title  ... Hotel_name_ibis Chennai Sipcot
2236                          average room  ...                              0
668        great location business cramped  ...                              0
2005  nice hotel or close beach chennai dt  ...                              0
808              good hotel prime location  ...                              0
2053             nice hotel costly add ons  ...                              0
...                                    ...  ...                            ...
674                    ideal business stay  ...                              0
1027            excellent stay value money  ...                              0
447            top notch hotel great hotel  ...                              0
1780                          hotel review  ...                              0
1014             old rooms need renovation  ...                              0

[706 rows x 4466 columns]

In [ ]:
df_test

                                Review_Title  ... Hotel_name_ibis Chennai Sipcot
0                                  mr neural  ...                              0
1                                great still  ...                              0
2                 nice stay corporate people  ...                              0
3                              average hotel  ...                              0
4             good mid range corporate hotel  ...                              0
...                                      ...  ...                            ...
2347                            average stay  ...                              0
2348  location good rude behavior staff help  ...                              0
2349                         quality service  ...                              0
2350                    rat overpriced hotel  ...                              0
2351                        nice beach hotel  ...                              0

[2352 rows x 3975 columns]

Сохраню, чтобы впоследствии загрузить и продолжить выполнение домашки

In [ ]:
!ls /content/MyDrive/MyDrive/тексты/copies/

In [ ]:
X_train.to_csv('/content/MyDrive/MyDrive/тексты/copies/X_train.csv')
X_test.to_csv('/content/MyDrive/MyDrive/тексты/copies/X_test.csv')
y_train.to_csv('/content/MyDrive/MyDrive/тексты/copies/y_train.csv')
y_test.to_csv('/content/MyDrive/MyDrive/тексты/copies/y_test.csv')

In [ ]:
df.to_csv('/content/MyDrive/MyDrive/тексты/copies/df.csv')

In [ ]:
df_test.to_csv('/content/MyDrive/MyDrive/тексты/copies/df_test.csv')

In [ ]:
X_train = pd.read_csv('/content/MyDrive/MyDrive/тексты/copies/X_train.csv')
X_test = pd.read_csv('/content/MyDrive/MyDrive/тексты/copies/X_test.csv')

In [ ]:
y_train = pd.read_csv('/content/MyDrive/MyDrive/тексты/copies/y_train.csv')
y_test = pd.read_csv('/content/MyDrive/MyDrive/тексты/copies/y_test.csv')

In [ ]:
X_train.drop(['Review_Text', 'Review_Title'], axis=1, inplace=True)
X_test.drop(['Review_Text', 'Review_Title'], axis=1, inplace=True)

In [ ]:
df_test.drop(['Review_Text', 'Review_Title'], axis=1, inplace=True)

оставим колонки, которые есть и в тесте и в трейне

In [ ]:
unwanted_columns_test = list(set(X_test.columns).difference(set(X_train.columns)))
unwanted_columns_train = list(set(X_train.columns).difference(set(X_test.columns)))

In [ ]:
X_test.drop(labels=unwanted_columns_test, axis=1, inplace=True)
X_train.drop(labels=unwanted_columns_train, axis=1, inplace=True)

In [ ]:
y_test.drop('Unnamed: 0', axis=1, inplace=True)
y_train.drop('Unnamed: 0', axis=1, inplace=True)

In [ ]:
X_train.drop('Unnamed: 0', axis=1, inplace=True)
X_test.drop('Unnamed: 0', axis=1, inplace=True)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred_lin_reg = lin_reg.predict(X_test)
mean_squared_error(y_test, y_pred_lin_reg)

466.8728497167147

In [ ]:
pd.DataFrame(data={'y_pred_lin_reg': np.array(y_pred_lin_reg).reshape(-1),
                   'y_real': np.array(y_test).reshape(-1)})

     y_pred_lin_reg  y_real
0         74.474560      57
1         53.886476      60
2         79.858488     100
3        104.794614      86
4        102.505464      80
..              ...     ...
701       76.659967      86
702      109.965197     100
703       97.312890     100
704       39.865608      43
705       73.668580      65

[706 rows x 2 columns]

In [ ]:
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
mean_squared_error(y_test, y_pred_rf)

224.6026971671388

In [ ]:
mean_squared_error(y_test, y_pred_rf, squared=False)

14.986750720791308

In [ ]:
pd.DataFrame(data={'y_pred_random_forest': np.array(y_pred_rf).reshape(-1),
                   'y_real': np.array(y_test).reshape(-1)})

     y_pred_random_forest  y_real
0                   64.59      57
1                   60.27      60
2                   76.09     100
3                   71.67      86
4                   67.38      80
..                    ...     ...
701                 84.77      86
702                 87.46     100
703                 84.63     100
704                 72.48      43
705                 56.56      65

[706 rows x 2 columns]

In [ ]:
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred_log_reg = log_reg.predict(X_test)
accuracy_score(y_test, y_pred_log_reg)

0.37535410764872523

In [ ]:
pd.DataFrame(data={'y_pred_log_reg': y_pred_log_reg.reshape(-1),
                   'y_real': y_test.values.reshape(-1)})

     y_pred_log_reg  y_real
0                71      57
1                71      60
2               100     100
3                71      86
4               100      80
..              ...     ...
701             100      86
702             100     100
703             100     100
704              71      43
705              80      65

[706 rows x 2 columns]

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print(accuracy_score(y_test, y_pred_rf))
mean_squared_error(y_test, y_pred_rf)

0.5354107648725213

298.8470254957507

In [ ]:
set(df.Rating)

{20.0, 29.0, 40.0, 43.0, 57.0, 60.0, 65.0, 71.0, 80.0, 86.0, 100.0}

Если решать эту задачу как задачу классификации, наша модель сможет предсказывать только один из 11 классов, когда в тесте значение таргета может и не принадлежать к одному из этих 11 классов. Поэтому дальше я буду решать эту задачу как задачу регрессии

Пока лучшая модель - случайный лес

Попробуем воспользоваться нормализацией данных

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline

In [ ]:
X_train_ss = StandardScaler().fit_transform(X_train)
X_test_ss = StandardScaler().fit_transform(X_test)

In [ ]:
X_train_mm = MinMaxScaler().fit_transform(X_train)
X_test_mm = MinMaxScaler().fit_transform(X_test)

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(X_train_mm, y_train)
y_pred_lin_reg = lin_reg.predict(X_test_mm)
mean_squared_error(y_test, y_pred_lin_reg)

530.0995404859555

In [ ]:
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train_mm, y_train)
y_pred_rf = rf.predict(X_test_mm)
mean_squared_error(y_test, y_pred_rf)

230.67462195467425

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(X_train_ss, y_train)
y_pred_lin_reg = lin_reg.predict(X_test_ss)
mean_squared_error(y_test, y_pred_lin_reg)

378.39585238845234

In [ ]:
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train_ss, y_train)
y_pred_rf = rf.predict(X_test_ss)
mean_squared_error(y_test, y_pred_rf)

221.36656968838528

rf дает результат лучше вместе с StandardScaler

In [ ]:
rf = RandomForestRegressor(random_state=42)
rf.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_rf = rf.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_rf)

221.36656968838528

In [ ]:
rf = RandomForestRegressor(n_estimators=1000, random_state=42)
rf.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_rf = rf.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_rf)

217.82525001699716

In [ ]:
rf = RandomForestRegressor(max_features='sqrt', random_state=42)
rf.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_rf = rf.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_rf)

205.33575807365438

In [ ]:
rf = RandomForestRegressor(n_estimators=70, max_features='sqrt', criterion='absolute_error', random_state=42)
rf.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_rf = rf.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_rf)

202.98078828698615

In [ ]:
y_pred_rf[(y_pred_rf > 100) | (y_pred_rf < 0)]

array([], dtype=float64)

In [ ]:
results = []
for max_features in ('sqrt', 'auto'):
    for n_estimators in range(50, 110, 10):
        for criterion in ('squared_error', 'absolute_error'):
            for max_depth in np.append(np.arange(2, 12, 2), None):
                rf = RandomForestRegressor(
                    max_features=max_features,
                    n_estimators=n_estimators,
                    criterion=criterion,
                    max_depth=max_depth,
                    random_state=42)
                rf.fit(StandardScaler().fit_transform(X_train), y_train)
                y_pred_rf = rf.predict(StandardScaler().fit_transform(X_test))
                result = (max_features, n_estimators, criterion, max_depth, mean_squared_error(y_test, y_pred_rf))
                results.append(result)
                print('max_features={}, n_estimators={}, criterion={}, max_depth={}, MSE={}'.format(*result))

max_features=sqrt, n_estimators=50, criterion=squared_error, max_depth=2, MSE=393.52731184928336
max_features=sqrt, n_estimators=50, criterion=squared_error, max_depth=4, MSE=366.6855294655442
max_features=sqrt, n_estimators=50, criterion=squared_error, max_depth=6, MSE=341.40600005092676
max_features=sqrt, n_estimators=50, criterion=squared_error, max_depth=8, MSE=323.18220040567275
max_features=sqrt, n_estimators=50, criterion=squared_error, max_depth=10, MSE=308.1282972142577
max_features=sqrt, n_estimators=50, criterion=squared_error, max_depth=None, MSE=210.08458866855526
max_features=sqrt, n_estimators=50, criterion=absolute_error, max_depth=2, MSE=407.20840807365437
max_features=sqrt, n_estimators=50, criterion=absolute_error, max_depth=4, MSE=363.27013016997165
max_features=sqrt, n_estimators=50, criterion=absolute_error, max_depth=6, MSE=346.0515371104816
max_features=sqrt, n_estimators=50, criterion=absolute_error, max_depth=8, MSE=328.3238287535411
max_features=sqrt, n_estimators=50, criterion=absolute_error, max_depth=10, MSE=309.6555056657224
max_features=sqrt, n_estimators=50, criterion=absolute_error, max_depth=None, MSE=208.1477597733711
max_features=sqrt, n_estimators=60, criterion=squared_error, max_depth=2, MSE=387.53088491789543
max_features=sqrt, n_estimators=60, criterion=squared_error, max_depth=4, MSE=360.40089791676587
max_features=sqrt, n_estimators=60, criterion=squared_error, max_depth=6, MSE=335.47722153712766
max_features=sqrt, n_estimators=60, criterion=squared_error, max_depth=8, MSE=317.0627093777219
max_features=sqrt, n_estimators=60, criterion=squared_error, max_depth=10, MSE=302.23216762701384
max_features=sqrt, n_estimators=60, criterion=squared_error, max_depth=None, MSE=206.2447816336166
max_features=sqrt, n_estimators=60, criterion=absolute_error, max_depth=2, MSE=398.0375120003148
max_features=sqrt, n_estimators=60, criterion=absolute_error, max_depth=4, MSE=360.23527256452627
max_features=sqrt, n_estimators=60, criterion=absolute_error, max_depth=6, MSE=340.1826383970727
max_features=sqrt, n_estimators=60, criterion=absolute_error, max_depth=8, MSE=322.3612104579792
max_features=sqrt, n_estimators=60, criterion=absolute_error, max_depth=10, MSE=306.22855474897705
max_features=sqrt, n_estimators=60, criterion=absolute_error, max_depth=None, MSE=205.65538125590177
max_features=sqrt, n_estimators=70, criterion=squared_error, max_depth=2, MSE=387.37213255593895
max_features=sqrt, n_estimators=70, criterion=squared_error, max_depth=4, MSE=360.5956030460744
max_features=sqrt, n_estimators=70, criterion=squared_error, max_depth=6, MSE=335.92478608121195
max_features=sqrt, n_estimators=70, criterion=squared_error, max_depth=8, MSE=317.1495765916778
max_features=sqrt, n_estimators=70, criterion=squared_error, max_depth=10, MSE=301.827427280759
max_features=sqrt, n_estimators=70, criterion=squared_error, max_depth=None, MSE=204.49091865641438
max_features=sqrt, n_estimators=70, criterion=absolute_error, max_depth=2, MSE=398.26033806440415
max_features=sqrt, n_estimators=70, criterion=absolute_error, max_depth=4, MSE=360.28420557033013
max_features=sqrt, n_estimators=70, criterion=absolute_error, max_depth=6, MSE=339.0275421315835
max_features=sqrt, n_estimators=70, criterion=absolute_error, max_depth=8, MSE=322.2178262849049
max_features=sqrt, n_estimators=70, criterion=absolute_error, max_depth=10, MSE=305.1430549372724
max_features=sqrt, n_estimators=70, criterion=absolute_error, max_depth=None, MSE=202.98078828698615
max_features=sqrt, n_estimators=80, criterion=squared_error, max_depth=2, MSE=388.83896465469945
max_features=sqrt, n_estimators=80, criterion=squared_error, max_depth=4, MSE=362.6585506927396
max_features=sqrt, n_estimators=80, criterion=squared_error, max_depth=6, MSE=338.5814612771492
max_features=sqrt, n_estimators=80, criterion=squared_error, max_depth=8, MSE=319.14319112290474
max_features=sqrt, n_estimators=80, criterion=squared_error, max_depth=10, MSE=302.4077440011553
max_features=sqrt, n_estimators=80, criterion=squared_error, max_depth=None, MSE=204.9050289925637
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=2, MSE=400.3054146932543
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=4, MSE=363.37789543865085
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=6, MSE=342.0178958259561
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=8, MSE=324.2875729240439
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=10, MSE=306.9904266443874
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=None, MSE=201.99047959454674
max_features=sqrt, n_estimators=90, criterion=squared_error, max_depth=2, MSE=390.21458494472785
max_features=sqrt, n_estimators=90, criterion=squared_error, max_depth=4, MSE=365.65603794092016
max_features=sqrt, n_estimators=90, criterion=squared_error, max_depth=6, MSE=339.67382116764276
max_features=sqrt, n_estimators=90, criterion=squared_error, max_depth=8, MSE=319.00223294106485
max_features=sqrt, n_estimators=90, criterion=squared_error, max_depth=10, MSE=303.2099798842812
max_features=sqrt, n_estimators=90, criterion=squared_error, max_depth=None, MSE=204.9864881264645
max_features=sqrt, n_estimators=90, criterion=absolute_error, max_depth=2, MSE=402.3608069282692
max_features=sqrt, n_estimators=90, criterion=absolute_error, max_depth=4, MSE=367.96346404714444
max_features=sqrt, n_estimators=90, criterion=absolute_error, max_depth=6, MSE=342.5292673469031
max_features=sqrt, n_estimators=90, criterion=absolute_error, max_depth=8, MSE=321.8284629105026
max_features=sqrt, n_estimators=90, criterion=absolute_error, max_depth=10, MSE=306.6607472982898
max_features=sqrt, n_estimators=90, criterion=absolute_error, max_depth=None, MSE=203.02573147273807
max_features=sqrt, n_estimators=100, criterion=squared_error, max_depth=2, MSE=391.4094273146432
max_features=sqrt, n_estimators=100, criterion=squared_error, max_depth=4, MSE=365.91660176450466
max_features=sqrt, n_estimators=100, criterion=squared_error, max_depth=6, MSE=340.67152393322715
max_features=sqrt, n_estimators=100, criterion=squared_error, max_depth=8, MSE=319.7285316495425
max_features=sqrt, n_estimators=100, criterion=squared_error, max_depth=10, MSE=304.2468097275445
max_features=sqrt, n_estimators=100, criterion=squared_error, max_depth=None, MSE=205.33575807365438
max_features=sqrt, n_estimators=100, criterion=absolute_error, max_depth=2, MSE=404.42166859065156
max_features=sqrt, n_estimators=100, criterion=absolute_error, max_depth=4, MSE=369.65193594192635
max_features=sqrt, n_estimators=100, criterion=absolute_error, max_depth=6, MSE=342.5994327903683
max_features=sqrt, n_estimators=100, criterion=absolute_error, max_depth=8, MSE=322.9459321529745
max_features=sqrt, n_estimators=100, criterion=absolute_error, max_depth=10, MSE=305.6214630311615
max_features=sqrt, n_estimators=100, criterion=absolute_error, max_depth=None, MSE=202.3418031161473
max_features=auto, n_estimators=50, criterion=squared_error, max_depth=2, MSE=312.22455487712756
max_features=auto, n_estimators=50, criterion=squared_error, max_depth=4, MSE=274.48787180458504
max_features=auto, n_estimators=50, criterion=squared_error, max_depth=6, MSE=259.86868463055697
max_features=auto, n_estimators=50, criterion=squared_error, max_depth=8, MSE=249.43421086542858
max_features=auto, n_estimators=50, criterion=squared_error, max_depth=10, MSE=245.37326007552687
max_features=auto, n_estimators=50, criterion=squared_error, max_depth=None, MSE=222.74338186968842
max_features=auto, n_estimators=50, criterion=absolute_error, max_depth=2, MSE=315.4899767705382
max_features=auto, n_estimators=50, criterion=absolute_error, max_depth=4, MSE=282.54096529745044
max_features=auto, n_estimators=50, criterion=absolute_error, max_depth=6, MSE=266.0764296033994
max_features=auto, n_estimators=50, criterion=absolute_error, max_depth=8, MSE=252.91382379603402
max_features=auto, n_estimators=50, criterion=absolute_error, max_depth=10, MSE=245.11882252124647
max_features=auto, n_estimators=50, criterion=absolute_error, max_depth=None, MSE=215.59341303116148
max_features=auto, n_estimators=60, criterion=squared_error, max_depth=2, MSE=311.61600139243376
max_features=auto, n_estimators=60, criterion=squared_error, max_depth=4, MSE=273.69073207520745
max_features=auto, n_estimators=60, criterion=squared_error, max_depth=6, MSE=259.93757930233045
max_features=auto, n_estimators=60, criterion=squared_error, max_depth=8, MSE=248.29444389187387
max_features=auto, n_estimators=60, criterion=squared_error, max_depth=10, MSE=244.127274843778
max_features=auto, n_estimators=60, criterion=squared_error, max_depth=None, MSE=220.75783876298397
max_features=auto, n_estimators=60, criterion=absolute_error, max_depth=2, MSE=315.44320900220333
max_features=auto, n_estimators=60, criterion=absolute_error, max_depth=4, MSE=282.68026066257477
max_features=auto, n_estimators=60, criterion=absolute_error, max_depth=6, MSE=265.18855701133145
max_features=auto, n_estimators=60, criterion=absolute_error, max_depth=8, MSE=252.7600264597104
max_features=auto, n_estimators=60, criterion=absolute_error, max_depth=10, MSE=244.88173355366695
max_features=auto, n_estimators=60, criterion=absolute_error, max_depth=None, MSE=213.86762826565942
max_features=auto, n_estimators=70, criterion=squared_error, max_depth=2, MSE=313.071124252875
max_features=auto, n_estimators=70, criterion=squared_error, max_depth=4, MSE=274.3302501384909
max_features=auto, n_estimators=70, criterion=squared_error, max_depth=6, MSE=260.1770247198656
max_features=auto, n_estimators=70, criterion=squared_error, max_depth=8, MSE=249.4037928971213
max_features=auto, n_estimators=70, criterion=squared_error, max_depth=10, MSE=244.29312869226888
max_features=auto, n_estimators=70, criterion=squared_error, max_depth=None, MSE=221.19450569462913
max_features=auto, n_estimators=70, criterion=absolute_error, max_depth=2, MSE=315.45765689136846
max_features=auto, n_estimators=70, criterion=absolute_error, max_depth=4, MSE=282.32637213100537
max_features=auto, n_estimators=70, criterion=absolute_error, max_depth=6, MSE=266.06257609701106
max_features=auto, n_estimators=70, criterion=absolute_error, max_depth=8, MSE=251.8588802248945
max_features=auto, n_estimators=70, criterion=absolute_error, max_depth=10, MSE=244.70437510840028
max_features=auto, n_estimators=70, criterion=absolute_error, max_depth=None, MSE=213.9428765103775
max_features=auto, n_estimators=80, criterion=squared_error, max_depth=2, MSE=313.05903081065344
max_features=auto, n_estimators=80, criterion=squared_error, max_depth=4, MSE=276.0410096942602
max_features=auto, n_estimators=80, criterion=squared_error, max_depth=6, MSE=260.92373438558315
max_features=auto, n_estimators=80, criterion=squared_error, max_depth=8, MSE=250.0553582955319
max_features=auto, n_estimators=80, criterion=squared_error, max_depth=10, MSE=244.63236462954316
max_features=auto, n_estimators=80, criterion=squared_error, max_depth=None, MSE=220.7281451398725
max_features=auto, n_estimators=80, criterion=absolute_error, max_depth=2, MSE=316.4801942612429
max_features=auto, n_estimators=80, criterion=absolute_error, max_depth=4, MSE=283.70346682453965
max_features=auto, n_estimators=80, criterion=absolute_error, max_depth=6, MSE=266.42221267484064
max_features=auto, n_estimators=80, criterion=absolute_error, max_depth=8, MSE=251.98359828700427
max_features=auto, n_estimators=80, criterion=absolute_error, max_depth=10, MSE=244.2062070644476
max_features=auto, n_estimators=80, criterion=absolute_error, max_depth=None, MSE=213.18530298335696
max_features=auto, n_estimators=90, criterion=squared_error, max_depth=2, MSE=312.0264390541143
max_features=auto, n_estimators=90, criterion=squared_error, max_depth=4, MSE=275.0140395876745
max_features=auto, n_estimators=90, criterion=squared_error, max_depth=6, MSE=260.2475635430629
max_features=auto, n_estimators=90, criterion=squared_error, max_depth=8, MSE=249.06286174304336
max_features=auto, n_estimators=90, criterion=squared_error, max_depth=10, MSE=243.06700682670544
max_features=auto, n_estimators=90, criterion=squared_error, max_depth=None, MSE=220.13815129577168
max_features=auto, n_estimators=90, criterion=absolute_error, max_depth=2, MSE=314.11813446472917
max_features=auto, n_estimators=90, criterion=absolute_error, max_depth=4, MSE=281.54615775714336
max_features=auto, n_estimators=90, criterion=absolute_error, max_depth=6, MSE=265.1268696009513
max_features=auto, n_estimators=90, criterion=absolute_error, max_depth=8, MSE=250.98013211275483
max_features=auto, n_estimators=90, criterion=absolute_error, max_depth=10, MSE=243.02429313992937
max_features=auto, n_estimators=90, criterion=absolute_error, max_depth=None, MSE=211.73977494491658
max_features=auto, n_estimators=100, criterion=squared_error, max_depth=2, MSE=311.818977472171
max_features=auto, n_estimators=100, criterion=squared_error, max_depth=4, MSE=275.03546432206866
max_features=auto, n_estimators=100, criterion=squared_error, max_depth=6, MSE=260.4180153005113
max_features=auto, n_estimators=100, criterion=squared_error, max_depth=8, MSE=249.61014120947277
max_features=auto, n_estimators=100, criterion=squared_error, max_depth=10, MSE=243.32956023472215
max_features=auto, n_estimators=100, criterion=squared_error, max_depth=None, MSE=221.36656968838528
max_features=auto, n_estimators=100, criterion=absolute_error, max_depth=2, MSE=312.9908061614731
max_features=auto, n_estimators=100, criterion=absolute_error, max_depth=4, MSE=280.2464913243626
max_features=auto, n_estimators=100, criterion=absolute_error, max_depth=6, MSE=263.90150701133143
max_features=auto, n_estimators=100, criterion=absolute_error, max_depth=8, MSE=250.23402889518414
max_features=auto, n_estimators=100, criterion=absolute_error, max_depth=10, MSE=242.7474753895184
max_features=auto, n_estimators=100, criterion=absolute_error, max_depth=None, MSE=211.7681279036827

In [ ]:
print('the best result:')
print('max_features={}, n_estimators={}, criterion={}, max_depth={}, MSE={}'.format(*min(results, key=lambda x: x[4])))

the best result:
max_features=sqrt, n_estimators=80, criterion=absolute_error, max_depth=None, MSE=201.99047959454674

In [ ]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.7/dist-packages (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from lightgbm) (1.4.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from lightgbm) (1.0.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from lightgbm) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->lightgbm) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->lightgbm) (3.0.0)

In [ ]:
from lightgbm import LGBMRegressor

In [ ]:
lgbm = LGBMRegressor(boosting_type='gbdt', num_leaves=50, n_estimators=100, random_state=42)
lgbm.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_lgbm = rf.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_lgbm)

211.7681279036827

Попереберал гиперпараметры у lgbm, лучше 211 результата добиться не удалось, random forest побеждает

In [ ]:
rf = RandomForestRegressor(n_estimators=80, max_features='sqrt', criterion='absolute_error', random_state=42)
rf.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_rf = rf.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_rf)

201.99047959454674

In [ ]:
df_test

      Review_Title_Missed  ...  Hotel_name_ibis Chennai Sipcot
0                       0  ...                               0
1                       1  ...                               0
2                       0  ...                               0
3                       0  ...                               0
4                       0  ...                               0
...                   ...  ...                             ...
2347                    0  ...                               0
2348                    0  ...                               0
2349                    1  ...                               0
2350                    0  ...                               0
2351                    0  ...                               0

[2352 rows x 3973 columns]

In [ ]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [ ]:
# define the base models
level0 = list()
level0.append(('knn', KNeighborsRegressor()))
level0.append(('cart', rf))
level0.append(('svm', SVR()))
level0.append(('lgbm', lgbm))
# define meta learner model
level1 = LinearRegression()
# define the stacking ensemble
stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

In [ ]:
stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

180.86553918310875

Удалось неплохо-таки улучшить результат, продолжим)

In [ ]:
level0 = list()
level0.append(('knn', KNeighborsRegressor()))
level0.append(('cart', rf))
# level0.append(('svm', SVR()))
level0.append(('lgbm', lgbm))

level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

180.89909732185302

In [ ]:
level0 = list()
# level0.append(('knn', KNeighborsRegressor()))
level0.append(('cart', rf))
# level0.append(('svm', SVR()))
level0.append(('lgbm', lgbm))

level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

180.78643124704976

In [ ]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.7/dist-packages (0.90)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from xgboost) (1.19.5)

In [ ]:
import xgboost as xgb

In [ ]:
level0 = list()
level0.append(('xgb', xgb.XGBRegressor(random_state=42)))
level0.append(('cart', rf))
# level0.append(('svm', SVR()))
level0.append(('lgbm', lgbm))

level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

[19:01:20] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:02:05] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:02:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:02:31] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:02:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:02:57] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

181.32182359141825

In [ ]:
level0 = list()
level0.append(('xgb', xgb.XGBRegressor(random_state=42)))
level0.append(('cart', rf))
# level0.append(('svm', SVR()))
level0.append(('lgbm', lgbm))

level1 = RandomForestRegressor(random_state=42)

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

[19:04:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:05:07] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:05:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:05:29] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:05:40] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:05:51] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

219.5535035410765

In [ ]:
level0 = list()
level0.append(('xgb', xgb.XGBRegressor(random_state=42)))
level0.append(('cart', rf))
level0.append(('knn', KNeighborsRegressor()))
level0.append(('svm', SVR()))
level0.append(('lgbm', lgbm))

level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

[19:07:25] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:08:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:08:20] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:08:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:08:43] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:08:54] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

181.33946843016105

Итоговая модель:

In [ ]:
level0 =[('cart', rf), ('lgbm', lgbm)]
level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), y_train)
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(y_test, y_pred_stack)

180.78643124704976

случайно поставил дефолтные гиперпараметры для lgbm, результат так оказался совсем немного лучше

In [ ]:
lgbm = LGBMRegressor()

In [ ]:
level0 =[('cart', rf), ('lgbm', lgbm)]
level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(X_train), np.array(y_train).ravel())
y_pred_stack = stack.predict(StandardScaler().fit_transform(X_test))
mean_squared_error(np.array(y_test).ravel(), y_pred_stack)

179.48920947664465

In [ ]:
pd.DataFrame(data={'y_test': np.array(y_test).ravel(),
                   'y_pred_stack': y_pred_stack})[:40]

    y_test  y_pred_stack
0     57.0     61.925604
1     60.0     65.201513
2    100.0     87.907782
3     86.0     77.627613
4     80.0     74.790181
5    100.0     90.377461
6     40.0     60.724056
7     65.0     64.978856
8     60.0     46.475077
9     86.0     74.456886
10   100.0     93.571831
11    86.0     88.773451
12    86.0     67.224423
13    57.0     61.894700
14    86.0     77.065955
15    40.0     42.692305
16    60.0     70.221794
17    40.0     60.813364
18    80.0     90.836757
19   100.0     87.093772
20    43.0     42.417160
21    80.0     81.012502
22    57.0     49.378880
23    57.0     57.455806
24   100.0    103.267258
25    40.0     56.358269
26    80.0     81.734606
27    20.0     47.477300
28    65.0     69.639881
29    80.0     92.891422
30   100.0     82.945553
31   100.0     97.149888
32    71.0     74.014363
33   100.0     91.521456
34    86.0     67.224423
35    86.0     81.515511
36    80.0     75.264550
37    86.0     66.453314
38    86.0     74.764404
39    80.0     83.239127

In [ ]:
y_pred_stack[(y_pred_stack > 100)|(y_pred_stack < 0)]

array([103.26725818, 101.21589788, 103.26725818, 100.62303579,
       104.8265756 , 101.01397216])

In [ ]:
y_pred_stack[y_pred_stack > 100] = 100

Итоговый результат для train.csv:

In [ ]:
mean_squared_error(y_test, y_pred_stack)

179.42187165107424

In [ ]:
mean_squared_error(y_test, y_pred_stack, squared=False)

13.394844965548286

In [ ]:
df.drop(['Hotel_name','Review_Title', 'Review_Text'], axis=1, inplace=True)

df - мой трейн, df_test - тест

оставим колонки, которые есть и в тесте и в трейне

In [ ]:
unwanted_columns_test = list(set(df_test.columns).difference(set(df.drop('Rating', axis=1).columns)))
unwanted_columns_train = list(set(df.drop('Rating', axis=1).columns).difference(set(df_test.columns)))

In [ ]:
df_test.drop(labels=unwanted_columns_test, axis=1, inplace=True)
df.drop(labels=unwanted_columns_train, axis=1, inplace=True)

In [ ]:
level0 =[('cart', rf), ('lgbm', lgbm)]
level1 = LinearRegression()

stack = StackingRegressor(estimators=level0, final_estimator=level1, cv=5)

stack.fit(StandardScaler().fit_transform(df.drop('Rating', axis=1)), df.Rating)
y_pred = stack.predict(StandardScaler().fit_transform(df_test))

In [ ]:
pd.Series(y_pred).to_csv('/content/MyDrive/MyDrive/тексты/copies/y_pred.csv')

In [ ]:
test = pd.read_csv('/content/MyDrive/MyDrive/тексты/дз/test.csv', encoding='ISO-8859-1')
pd.DataFrame(data={'review_title': test.Review_Title,
                   'review_text': test.Review_Text,
                   'y_pred_stack': y_pred})[:20]

                               review_title  ... y_pred_stack
0                                 Mr Neeraj  ...    67.961188
1                                       NaN  ...    79.912319
2            Nice stay for corporate people  ...    74.727441
3                             Average hotel  ...    55.270897
4          A good mid range corporate hotel  ...    73.335049
5                                 Good stay  ...    77.258093
6                  Wonderful stay at Savera  ...    66.619894
7                              Average stay  ...    56.679057
8                        Services are worst  ...    48.885629
9     Not bad at all... esp. for the price.  ...    53.574039
10                      June2016 in Chennai  ...    61.542767
11  Good for stay but not more than one day  ...    78.544835
12   Great experience but slow room service  ...    62.901770
13                                      NaN  ...    84.917747
14         Other than proximity not is good  ...    62.526079
15                                      NaN  ...    80.161464
16                      Not worth the money  ...    70.237395
17               Good Hotel with nice staff  ...    79.254989
18           Good stay with reasonable rate  ...    80.115928
19                           Busy traveller  ...    74.899616

[20 rows x 3 columns]

что было сделано:

In [ ]:
# TO DO: 
# - train test split ✅ 
# - заменить наны на первые 2 слова текста ✅ 
# - добавить фичу об отсутствии заголовка отзыва ✅ 
# - добавить фичу количество хороших и плохих слов в тексте каждого отзыва ✅ 
# - добавить фичу количество хороших и плохих слов в заголовке каждого отзыва ✅ 
# - добавить фичу среднее количество хороших и плохих слов об отеле отдельно в тексте и заголовке✅
# - tf idf ✅  
# - добавить фичу на количество слов в тексте и заголовке отзыва (результат стал хуже) ❌
# - добавить фичу на отношение количества слов в тексте отзыва и количества слов в заголовке отзыва (результат стал хуже) ❌
# - PCA (результат стал хуже) ❌
# - не забыть test.csv ✅ 
# - попытаться улучшить скор ✅